### ISSUE TITLE
can't add own array to search in it?

### ISSUE THREAD

**Issue by BassamHabash** [kadoshms/ionic2-autocomplete#102]
AutoCompleteComponent.html:36 ERROR TypeError: Cannot read property 'replace' of undefined
    at BoldPrefix.transform (index.js:265)
    at checkAndUpdatePureExpressionInline ()

```
getResults(keyword: string) {
       return this.http.get(PATHS.SERVER_GET_ALL_PRIVILEGE).map((response) =>{
           let result =  response.json();
           result = JSON.parse(result.result);
           result =  result.filter(item => item.profile_name.toLowerCase().startsWith(keyword.toLowerCase()));
            return result.map(item => item.profile_name);
        });
}
```

in your file : 
```
  BoldPrefix.prototype.transform = function (value, keyword) {
        if (!keyword)
            return value;
        var /** @type {?} */ escaped_keyword = keyword.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
        return value.replace(new RegExp(escaped_keyword, 'gi'), function (str) { return str.bold(); });
    };
```

value is undefined;

**Comment by jensgorm** [comment]
I have the same problem...

**Comment by Mic75** [comment]
@BassamHabash  did you set the `labelAttribute` property in your `AutoCompleteService` implementation ? If yes, this is the reason, as you're returning an array of string literal (non-object) in your `getResult`.

**Comment by kadoshms** [comment]
Thanks @Mic75 .
@BassamHabash can you please attach an example of the data returned from your service?
