### ISSUE TITLE
Auto Complete not working inside form or ion-item

### ISSUE THREAD

**Issue by pymendez** [kadoshms/ionic2-autocomplete#104]
Is It possible to use this component with a form? 

I already have the auto-complete working, but when inside ion-content, if I put it inside a form in order to submit is value with the submit of the form or even inside an ion-item, outside the form, the auto-complete will not render properly.

Is there any way to use it that I couldn't found until now?

Thanks

**Comment by kadoshms** [comment]
possible duplicate of #95

**Comment by pymendez** [comment]
@kadoshms Thank you. I checked that issue, it was part of the solution but I was also having a trouble while adding it into a form as it was returning the error "No value accessor for form control with name".

I read some more documentation and find out that I have to add "ngDefaultControl" to the element because ion-auto-complete is not a know element to ngModel.

I can't remove the issue, but it's possible that this information is useful for more people looking for the answer, if you don't think so and you can remove it, it's ok.

Thanks.

**Comment by kadoshms** [comment]
One should never remove an issue :)
