### ISSUE TITLE
ng-template doesn't work by passing a function to dataProvider

### ISSUE THREAD

**Issue by bogomips** [kadoshms/ionic2-autocomplete#105]
The function returns a normal array of string, but the property attrs.data.name is empty

**Comment by kadoshms** [comment]
It worked perfectly to me:

My template:
```
  <ng-template #temp let-attrs="attrs">
    <span>{{attrs.data.name}}</span>
  </ng-template>
  <ion-auto-complete
                     [template]="temp"
                     [dataProvider]="auto" #searchbar></ion-auto-complete>
```

My provider:

```
  auto(keyword) {
    return [{name: 'a'}, {name: 'b'}];
  }
```
@bogomips I can guess that your provider function doesn't return the data in this form, am I right?
The value of `attrs.data` is the actual item value that is returned from the provider. If your items don't have a `name` proeperty, `attrs.data.name` will be empty.

Please update me

**Comment by kadoshms** [comment]
I am closing this for now.
The example Iv'e provided worked perfectly to me, if for any reason it still does not work for you, just let me know.
