### ISSUE TITLE
Error when show data with template 

### ISSUE THREAD

**Issue by phuclam85** [kadoshms/ionic2-autocomplete#106]
![screen shot 2017-09-24 at 12 26 21](https://user-images.githubusercontent.com/454179/30779774-d67db4ee-a123-11e7-817e-5dd9e8c5a664.png)

**Comment by kadoshms** [comment]
@phuclam85 please add more information (please attach your controller and template code).

**Comment by kadoshms** [comment]
Closing due to no response.
