### ISSUE TITLE
Click event on item in dropdown is getting propagated to any element under the dropdown

### ISSUE THREAD

**Issue by Hermiona** [kadoshms/ionic2-autocomplete#107]
I have a ion-auto-complete input and a button below it. When I select any item in opened dropdown of a ion-auto-complete the click event is propagated to the element under the dropdown, for example, to button

**Comment by ignacioPastor** [comment]
Same problem here. I have tried to clone the repo and fix it but stopPropagation() and many other attempts haven't worked. Seems that the event can't be stopped :s

**Comment by leo-staric** [comment]
Has anyone found a solution :(?

**Comment by ignacioPastor** [comment]
As terrible workaround, you can display an invisible layout behaind the searchbar and dropdown when dropdown is displayed and capture there the propagation. Not really good solution, but the only way a get it working (I tryed to download the code and fix it but there are a rare bug behaviour that doesn't allow to stop the propagation.

**Comment by JahBrewski** [comment]
@ignacioPastor curious what your solution looks like?

**Comment by ignacioPastor** [comment]
Put this div in your html, nor relevant where

`<div *ngIf="showTransparentPage" id="transparentPage"></div>`

`    #transparentPage { 
        position: absolute; 
        height: 100%; 
        width: 100%; 
        z-index: 9; 
    } `

In the html "showTransparentPage" is a boolean that I manage from the .ts, true when the searchBar gets the focus. If your searchBar has z-index: 10,  and the page's z-index is setted lower than 9, should work.
It's a workaround that I've done more than once when I'm in a hurry. But here I finally did what I needed by myself, It could be better than complicate so much your code.

**Comment by JanMisker** [comment]
I witnessed something similar, and also the dropdown was not closing when clicking elsewhere in the page. I figured out it has something to do with the document:click HostListener, it seems to not get triggered.

As a workaround I added a `@HostListener` in my own component, but on document:tap instead, I duplicated the content of the documentClickHandler in this function (referencing the AutoComplete component I get via `@ViewChild`) and this seems to work. I did have to put a timeOut on the hideList, because otherwise the event does not reach the dropdown list. 

 ```
 @HostListener('document:tap', ['$event'])
  clickout(event) {
    // clone of the documentClickHandler in autocomplete, seems document:click doesn't work
    if ((this.relationSuggest.searchbarElem && !this.relationSuggest.searchbarElem._elementRef.nativeElement.contains(event.target))
        || (!this.relationSuggest.inputElem && this.relationSuggest.inputElem._elementRef.nativeElement.contains(event.target))) {
      setTimeout(() => {
        this.relationSuggest.hideItemList();
      }, 50);
    }
  }
  @ViewChild(AutoCompleteComponent) relationSuggest: AutoCompleteComponent;

```

**Comment by bogomips** [comment]
Same here, any solution?

**Comment by jjibarrola** [comment]
Hi everybody,

I have found a solution for this problem. In my case i solved the problem modifiying the "tap" event its generated when we select an option.

Just change the following line in the file **autocomplete.component.ts**

`<li *ngFor="let suggestion of suggestions" (tap)="select(suggestion);$event.srcEvent.stopPropagation()">`

for this one
`<li *ngFor="let suggestion of suggestions" (click)="select(suggestion); $event.stopPropagation()">`

**Comment by olaisen81** [comment]
Same issue, any solution?

**Comment by eake** [comment]
With new version, it works now on ios, but on android I still have same issue.

**Comment by Anarhislav** [comment]
same issue, any fix?

**Comment by nosTa1337** [comment]
same issue on android.

**Comment by vkbrulex** [comment]
Simple fix on index.js  of this node module change  tap event with click event where select(suggestion) is fired and use $event.stopPropagation() instead of $event.srcEvent.stopPropagation().

Find **(tap)=\"select(suggestion);$event.srcEvent.stopPropagation()\"**  with control+f
and replace with 
**(click)=\"select(suggestion);$event.stopPropagation()\"**
and replace with 


turns out reason for the bug was bug in hammer.js

**Comment by vkbrulex** [comment]
Anarhislav open your  project goto node modules directory and open index.js  search and find (click)="select(suggestion);$event.stopPropagation() and replace with (tap)="select(suggestion);$event.srcEvent.stopPropagation() your issue will be fixed

**Comment by renanmoraes** [comment]
I'm using the "ionic2-auto-complete" version: "^ 1.6.2-alpha",
 but continue with the same error, which command to adjust this problem?

**Comment by kadoshms** [comment]
@Anarhislav this will be fixed someday in the near future, but unfortunatly as I stated before, I am not really available for maintaining the repo on a regular basis. You are more invited though to fork the repo and try the fix provided in the pull requests, and compile your own version :)
I promise I will dedicate some time anytime soon, but I can't tell when it will happen...

**Comment by renanmoraes** [comment]
Anyone who has experience to do that would love it, I'm not knowledgeable enough to generate these builds, but anyone who knows would greatly appreciate the help.

**Comment by quangpdt** [comment]
The fix is already merged to master but the latest version is not updated yet, sadly. Now the quickest way to fix this issue is fork this repo and make your own package on NPM

**Comment by presidentnickson** [comment]
> Anarhislav open your project goto node modules directory and in this plugin's module installation directory and open index.js search and find (click)="select(suggestion);$event.stopPropagation() and replace with (tap)="select(suggestion);$event.srcEvent.stopPropagation() your issue will be fixed

Still having the same issue when i change it from `(click)="select(suggestion);$event.stopPropagation()` to `(tap)="select(suggestion);$event.srcEvent.stopPropagation()` - is anyone else still having this problem ?

**Comment by Jai-A** [comment]
I am having the same issues with version 1.6.2-alpha i have tried changing: (tap)="select(suggestion);$event.srcEvent.stopPropagation() to (click)="select(suggestion);$event.srcEvent.stopPropagation() 
but then the event seems to be undefined resulting in this error

SearchRidersComponent.html:7 ERROR TypeError: Cannot read property 'stopPropagation' of undefined
    at Object.eval [as handleEvent] (AutoCompleteComponent.html:43)
    at handleEvent (core.js:13589)
    at callWithDebugContext (core.js:15098)
    at Object.debugHandleEvent [as handleEvent] (core.js:14685)
    at dispatchEvent (core.js:10004)
    at core.js:10629
    at HTMLLIElement.<anonymous> (platform-browser.js:2628)
    at t.invokeTask (polyfills.js:3)
    at Object.onInvokeTask (core.js:4751)
    at t.invokeTask (polyfills.js:3)

**Comment by Jai-A** [comment]
@vkbrulex I tried to use your version of the package but my ionic is complaining that it can't find the module. i have checked the node modules folder for the package and it is there and has the same name.

I installed the package using: 
npm install git+https://github.com/vkbrulex/ionic2-autocomplete.git --save

**Comment by dyegonery** [comment]
I published a version of this package for Ionic 3 in Npmjs with the same solution proposed by @vkbrulex: [ionic3-auto-complete](https://www.npmjs.com/package/ionic3-auto-complete).

It can be installed this way: npm install ionic3-auto-complete --save
