### ISSUE TITLE
Get selected item from json ?

### ISSUE THREAD

**Issue by zeroseed** [kadoshms/ionic2-autocomplete#11]
How to get selected item using (itemSelected) callback ?
eg : the data is {"name": "Indonesia", "currency":"IDR"}
how to get the "IDR" when event triggered ?
so i still want to showing "Indonesia" on input text but i need "IDR" as input value.

Thank you! 👍

**Comment by zaiderikat** [comment]
Still no answer, have you solved it ?

**Comment by zaiderikat** [comment]
Here is the solution: 
Add this to the page.html
`<ion-auto-complete [dataProvider]="completeTestService" (itemSelected)="getVal($event)"></ion-auto-complete>`

In the page.ts use this:

`
getVal($event){
    console.log($event);
  }
`
It will return the entire selected object.

**Comment by zeroseed** [comment]
Thanks but, did you mean entire selected object ?
what i mean is to get the value="" on option, not the entire text 
I already use getVal($event) it just give me option text not the option value

**Comment by kadoshms** [comment]
@zeroseed each entry is actually the object associated with the option within the implemented service.
That means, that there is no a "value" attribute, but any property associated with the options is reflected and is accessible.

**Comment by aleehpandita** [comment]
thank you so much @zaiderikat
