### ISSUE TITLE
show multiple data in autocomplete

### ISSUE THREAD

**Issue by kanchany21** [kadoshms/ionic2-autocomplete#110]
how to show city name with country

**Comment by kadoshms** [comment]
Please elaborate more, your description is not informative enoguh.

**Comment by kanchany21** [comment]
i want to show multiple data like country name with capital and region, as shown in below image 

![untitled](https://user-images.githubusercontent.com/32696795/31427693-fd562a0a-ae1c-11e7-831c-c17c04b4a6b3.png)

**Comment by kadoshms** [comment]
Have you considered using a custom template? 
This is exactly what it's meant for :)
Please reffer to the docs

**Comment by kadoshms** [comment]
Anyway I am closing this for now, if you need any further assistant with this don't hesitate.
