### ISSUE TITLE
Input validation

### ISSUE THREAD

**Issue by nosTa1337** [kadoshms/ionic2-autocomplete#112]
Hi,

is it possible to use the angular formgroup validation on the searchbar? 

I have a formgroup with validators and I would like to add the validator to the searchbar.

`this.formGroup = this.formBuilder.group({
      materialInternalId: ['', Validators.required],
      identifiedStockID: ['']....`

Any suggestions? It's just needed for the visual, I know I can check if it has a valid value or not.

//edit
To make it a bit clearer. I would like to use a normal input field with the possibility to use your autocomplete function. Would it be hard to change it that way or can you give me some hints where to do this?

Regards,
Philipp

**Comment by kadoshms** [comment]
@nosTa1337 It is not possible in the current version, would you like to make a PR for that?

**Comment by nosTa1337** [comment]
@kadoshms  You may saw my custom repo, but it's not customizable yet and I don't know if I find the time to do so. You can close this request. If I find the time I will do a PR.

**Comment by JeongJun-Lee** [comment]
Is there any update? is this feature possible now?
