### ISSUE TITLE
question: partial complete within a string based on a character/keyword

### ISSUE THREAD

**Issue by shie-erlich** [kadoshms/ionic2-autocomplete#116]
hi folks,
thanks for working on this project.
i have a more advanced need, and i'd like to know if i can somehow modify this component to make it work for me. basically, i have a textedit component in which i type free form strings, and i want the autocomplete to kick-in for a part of the string. 

example:
let's say i type "good morning @vie" -> i'd like the autocomplete to start completing after i type '@' and therefore show "vietnam"

or if i type "talk to @david about blah" -> i'd like autocomplete to kick in after the '@d', allow me to choose 'david' and then let me continue typing the rest of the string.

is this doable in any way?

thanks in advance for your help!

**Comment by kadoshms** [comment]
Hey @shie-erlich, what you are describing is actually pretty different from what this component stands for (search box with a list under it).
I believe though, that you can fork this repo and make those changes (there should be a lot of changes, but you can deffinetly find some of  the code base useful).

I am closing this as this is not a plugin issue, please feel fee to consult me and continue this discussion.
