### ISSUE TITLE
Error with ionic 3.9 and Angular 5: Can't bind to 'ngOutletContext' since it isn't a known property of 'ng-template'

### ISSUE THREAD

**Issue by mgoku** [kadoshms/ionic2-autocomplete#117]
Hi,

I try to use this library with ionic 3.9.2 and Angular 5, but it doesnt work.

The error message say:

```
Error: Template parse errors:
Can't bind to 'ngOutletContext' since it isn't a known property of 'ng-template'.
```
I check Angular API documentation, and it seems `ngOutletContex` has been deprecated in Angular 5.

https://angular.io/api/common/NgTemplateOutlet

I assume it can be fixed by replacing `ngOutletContex` with `ngTemplateOutletContex`.

**Comment by CoreyCole** [comment]
Looks to me as simple as your suggest from the same issue in ngx-chips  here: 
https://github.com/Gbuomprisco/ngx-chips/pull/585/commits/cd319822084bd57d2a9fbb2b783c532f5f587323

The depreciated ngOutletContext directive is only used here:
https://github.com/kadoshms/ionic2-autocomplete/blob/e63f60d6b65a5c015c706951b45b0df744833f76/src/autocomplete.component.ts#L69

Working on a PR...

**Comment by CoreyCole** [comment]
Does anyone know how to run the build so I can swap it out with the current version that is in my node_modules and test that it works? I have a suspicion that we will also need to upgrade the angular version to at least `^4.2.0` it have the `ngTemplateOutletContex` directive

**Comment by CoreyCole** [comment]
More information on updating moduleName for rollup: https://github.com/rollup/rollup/issues/1479

**Comment by kadoshms** [comment]
@CoreyCole thanks!

**Comment by mgoku** [comment]
Thank you

**Comment by en-sevilla** [comment]
I had the same issue on Ionic2-calendar (https://github.com/twinssbc/Ionic2-Calendar/issues/233) and I solved it by deleting   `[locale]="es-ES"` in the HTML component, by replacing this:

 ```
<calendar 
  [eventSource]="eventSource" 
  [calendarMode]="calendar.mode"
  [startingDayMonth]="calendar.startingDayMonth"
  formatMonthTitle="MMMM yyyy"
  startingDayWeek=1
  formatDayHeader="EEE"
  formatDayTitle="EEEE, dd MMMM yyyy"
  formatWeekTitle="'semana '$n, MMMM yyyy"
  [locale]="es-ES"
  [currentDate]="calendar.currentDate"
  [noEventsLabel]="calendar.noEventsLabel"
  [monthviewDisplayEventTemplate]="template"
  (onCurrentDateChanged)="onCurrentDateChanged($event)"
  (onEventSelected)="onEventSelected($event)"
  (onTitleChanged)="onViewTitleChanged($event)"
  (onTimeSelected)="onTimeSelected($event)"
  step="30">
  </calendar>
```

for this

 ```
<calendar 
  [eventSource]="eventSource" 
  [calendarMode]="calendar.mode"
  [startingDayMonth]="calendar.startingDayMonth"
  formatMonthTitle="MMMM yyyy"
  startingDayWeek=1
  formatDayHeader="EEE"
  formatDayTitle="EEEE, dd MMMM yyyy"
  formatWeekTitle="'semana '$n, MMMM yyyy"
  [currentDate]="calendar.currentDate"
  [noEventsLabel]="calendar.noEventsLabel"
  [monthviewDisplayEventTemplate]="template"
  (onCurrentDateChanged)="onCurrentDateChanged($event)"
  (onEventSelected)="onEventSelected($event)"
  (onTitleChanged)="onViewTitleChanged($event)"
  (onTimeSelected)="onTimeSelected($event)"
  step="30">
  </calendar>
```
for clarity sake, my app.module.ts is:

```
import { ErrorHandler, NgModule, LOCALE_ID } from '@angular/core';
import { registerLocaleData } from '@angular/common';
import localeES from '@angular/common/locales/es';
registerLocaleData(localeES);

[... common code here ...]

 providers: [
    { provide: LOCALE_ID, useValue: 'es-ES' },   //Ionic Calendar Localization
  ]
```
and ionic2-calendar is 0.4.0 version
