### ISSUE TITLE
I can't upgrade from 1.5.1 to 1.5.2 release

### ISSUE THREAD

**Issue by sofiane01234** [kadoshms/ionic2-autocomplete#119]
Hi there 
Thanks for the plugin but i have a trouble
when i download the version 1.5.2 with npm install i can't find the form angular validators inside 
any help ?? 

Ionic info :

: 1.9.2
ionic (Ionic CLI) : 3.9.2

global packages:

Cordova CLI : 7.0.1
local packages:

@ionic/app-scripts : 3.0.1
Cordova Platforms  : android 6.2.3
Ionic Framework    : ionic-angular 3.6.0
System:

Node : v6.11.1
npm  : 5.3.0
OS   : Windows 10

**Comment by sofiane01234** [comment]
Ionic info : 

  @ionic/cli-utils  : 1.9.2
    ionic (Ionic CLI) : 3.9.2

global packages:

    Cordova CLI : 7.0.1

local packages:

    @ionic/app-scripts : 3.0.1
    Cordova Platforms  : android 6.2.3
    Ionic Framework    : ionic-angular 3.6.0

System:

    Node : v6.11.1
    npm  : 5.3.0
    OS   : Windows 10

**Comment by kadoshms** [comment]
I am not sure I am following. The plugin does not have any built in validators support. Could you please elaborate more?

**Comment by kadoshms** [comment]
I am closing this due to no response.
