### ISSUE TITLE
getting unexpected value error while build process of android

### ISSUE THREAD

**Issue by vijaypatel** [kadoshms/ionic2-autocomplete#12]
[16:36:28]  Error: Unexpected value 'AUTOCOMPLETE_DIRECTIVES' declared by the module 'AppModule'

`    "ionic2-auto-complete": "^1.3.1",`
`import { AUTOCOMPLETE_DIRECTIVES, AUTOCOMPLETE_PIPES } from 'ionic2-auto-complete';

@NgModule({
  declarations: [
    MyApp,
    LoginPage,
    DefectSelectionPage,
    WagonSetInfoPage,
    HomePage,
    InspectionHistoryPage,
    ServiceHandlePage,
    SplashPage,
    WagonHoldInfoPage,
    WagonInspectionPage,
    WagonSearchPage,
    AUTOCOMPLETE_DIRECTIVES,
    AUTOCOMPLETE_PIPES    
  ],`

**Comment by mosca90** [comment]
Ionic 2 R5, with little adjustments, it works.
