### ISSUE TITLE
Angular 5

### ISSUE THREAD

**Issue by fortuneNext** [kadoshms/ionic2-autocomplete#120]
Hi,

using Angular 5, im getting the error:
> Can't bind to 'ngOutletContext' since it isn't a known property of 'ng-template'

Any plans to upgrade this awesome project to Angular 5?

Greetings!

**Comment by kadoshms** [comment]
Yes, there's already a branch for that :)
You are most welcome to make PR's anyway :)

**Comment by manuvalentim** [comment]
has solution? i need this plugin.
