### ISSUE TITLE
Custom Templates not working

### ISSUE THREAD

**Issue by mosca90** [kadoshms/ionic2-autocomplete#13]
Using custom templates and following your example, give error:
`More than one component matched on this element.
Make sure that only one component's selector can match a given element.
Conflicting components: AutoCompleteItemComponent,CompTestIte`

This is the extends:

`
@AutoCompleteItem({
  template : "<img /> - <span [innerHTML]="data.name | boldbegin:keyword"></span>"
})
export class CompTestItem extends AutoCompleteItemComponent{}
`

and this the call in HTML:
`<ion-auto-complete [dataProvider]="autocompleteProvider"></ion-auto-complete>`

**ps:** 
It would be great if you were to update the project and documentation to Ionic rc.5
Many things have changed

**Comment by kadoshms** [comment]
Please check in the new version :)
