### ISSUE TITLE
How exactly to pass a function as dataProvider?

### ISSUE THREAD

**Issue by fortuneNext** [kadoshms/ionic2-autocomplete#130]
Hi again,

the documentation says that it is possible to pass a simple function that returns an array as dataProvider but it is not documented how exactly the syntax for that is.

Im getting the error "TypeError: this.dataProvider.getResults is not a function" for the line

`<ion-auto-complete [dataProvider]="test"></ion-auto-complete>`

and error "_co.test is not a function" for the line

`<ion-auto-complete [dataProvider]="test()"></ion-auto-complete>`

where test is 

`test(): Array<string> {
   return ["1", "2"];
}`

Am I using it wrong?

Thanks!

**Comment by b-d055** [comment]
I am having this same issue. How did you resolve this? I can't seem to find the documentation for it.

**Comment by fortuneNext** [comment]
My working code looks like this:

`<ion-auto-complete`  [dataProvider]="aFunc.bind(this)"></ion-auto-complete>`

`aFunc(filter: string): Array<string> {
    return ["1","2"];
  }`

**Comment by mnibras** [comment]
@fortuneNext it's work for me. Thank you!!!

**Comment by Gregordy** [comment]
Yes thanks a lot, also working for me!!
Saved my day!
