### ISSUE TITLE
Empty the value of searchbar from controller

### ISSUE THREAD

**Issue by GREPY** [kadoshms/ionic2-autocomplete#135]
Hello, I'm new to Angular and I need help with this module.
I need to erase the string inside autocomplete component after item is selected, or space/enter key pressed. I use events itemSelected when item is selected and ionAutoInput when space is pressed - but it is not fired on enter key. I have 2 questions:

1. How can I bind event to enter key press when focused to autocomplete component?

2. How can I erase (make it empty) string inside autocomplete component from my controller?

Thanks!

**Comment by GREPY** [comment]
Will you help me, please? I assigned the model with ngModel but two way data binding is not working when I erase the model in controller.
And by event key press I meant tapping search (confirm) button on mobile keyboard.
Thank you.

**Comment by ar27111994** [comment]
same question.

**Comment by ar27111994** [comment]
ok got the solution: 
**Component Mapping to Controller**
`@ViewChild('nameFilter')nameFilter: AutoCompleteComponent;`
**Controller method code**
`this.nameFilter.clearValue();`

**Comment by GREPY** [comment]
Wonderful, thanks, now it works :) :+1: 

And what about capturing submit event?

**Comment by ar27111994** [comment]
Input fields don't have submit events, forms and buttons have it. You can use `nameFilter.getValue()` inside your `submit()` function to get the selected value in `AutoCompleteComponent` .

**Comment by GREPY** [comment]
Thank you, I put it inside the form :)

**Comment by JeongJun-Lee** [comment]
But I think it's still bug. The two-way binding by NgModel should work well.
