### ISSUE TITLE
Suggestions box doesn't show up despite successful HTTP response

### ISSUE THREAD

**Issue by ar27111994** [kadoshms/ionic2-autocomplete#138]
Hi, my suggestions are not showing in Ionic 3.9.2 and Angular 5.0.3. Please help! I've literally tried each and everything but search suggestions just won't show up. Please help! @kadoshms 

**Service Code:**
```
@Injectable()
export class FilterNameServiceProvider extends DataServiceProvider implements AutoCompleteService  {

    labelAttribute = "name"
    getResults(name: string) {
        return Observable.fromPromise(this.fetchData('product/autocomplete', { filter_name: name })).mergeMap((res) => {
            if(!res['isNotAuthenticated']) {
              delete res['isNotAuthenticated'];
              
              return res;
            }
        })
    }

}
```
**Template Code:**
```
<ion-header>
  <ion-toolbar>
    <ion-title>{{ button_filter | htmlDecode }}</ion-title>
    <ion-buttons start>
      <button ion-button icon-left clear item-start (click)="dismiss()">
        <ion-icon name="close-circle"></ion-icon>
      </button>
    </ion-buttons>
  </ion-toolbar>
</ion-header>

<ion-content>
      <ion-auto-complete class="overflow" item-content [(ngModel)]="filter_name" [dataProvider]="nameAutocomplete" [options]="{ placeholder: entry_name | htmlDecode }"></ion-auto-complete>
</ion-content>
```

**Fetched Response from Server:**
![err2](https://user-images.githubusercontent.com/13036687/34363238-2cd83e7e-ea9c-11e7-9dfe-ced3ae0a9eef.JPG)

**Browser Output:**
![err1](https://user-images.githubusercontent.com/13036687/34363243-424e9794-ea9c-11e7-9f27-41550dda066e.JPG)

even tried this CSS:
```

.overflow {
        contain: none; 
        overflow: visible;
 }
```

In addition, I've also tried using it without ngModel, used it in an Ionic page (instead of a Modal popup), used it inside an `ion-list`, used it without placeholder, used it with `dataprovider` returning a string array (instead of the current objects) from http observable, and even tried using it with a function instead of a service provider etc. But Alas! all in vain.

**Comment by kadoshms** [comment]
what version of the plugin are you using?

**Comment by ar27111994** [comment]
version `1.6.2-alpha`

**Comment by kadoshms** [comment]
@ar27111994 
when your'e running with `ionic serve` do you see any error in the console?

**Comment by ar27111994** [comment]
no, there's no error in the console. Here are the results of `getResults` 
![consoleout1](https://user-images.githubusercontent.com/13036687/34374093-f1ff4238-eb00-11e7-8838-8c73302196a6.JPG)
function:

**Comment by ar27111994** [comment]
![consoleout1-1](https://user-images.githubusercontent.com/13036687/34374128-311d5b6c-eb01-11e7-944a-fc391f48e3e0.JPG)

**Comment by kadoshms** [comment]
@ar27111994 well this is definitely odd.
Does it also happen when you are using it in a regular flat page? (I mean - without ion-list)?
I tried some pieces of your code and it seemed fine

**Comment by ar27111994** [comment]
yes, absolutely, I've tried it in a regular page in both header and content areas, but with the same result.

**Comment by ar27111994** [comment]
@kadoshms  maybe look at my service provider and see if I'm doing everything according to the docs? I hope that `labelAttribute` is the name of the property in each of the array objects that we wanna show in and select from the search suggestions.

**Comment by ar27111994** [comment]
even uninstalled and re-installed the `npm` package:
![consoleout2](https://user-images.githubusercontent.com/13036687/34374902-70ffff1a-eb05-11e7-9c48-e09823c27a57.JPG)
![consoleout3](https://user-images.githubusercontent.com/13036687/34374903-7131656e-eb05-11e7-872f-2ead3c64dfe5.JPG)

**Comment by ar27111994** [comment]
sorry, button pressed by mistake.

**Comment by ar27111994** [comment]
ok, I've finally got it working but with different code and without authentication check. Here's the updated code:

```
getResults(name: string) {
        return Observable.fromPromise(this.getData('api_token')).mergeMap((token) => {
              let postData = new FormData();
              postData.set("api_token", (token) ? token : ''); 
            return this.http.post(BASE_URL + API_URL + "product/autocomplete&filter_name=" + name, postData, {headers: this.headers})
            .map(
                result =>
                {
                return result;
                });
            }).catch(this.handleError);
    }
```

![screenshot from december 27 2017 3_37 pm](https://user-images.githubusercontent.com/13036687/34379317-816a1b62-eb1c-11e7-81b0-ff38396332fd.png)

**Comment by ar27111994** [comment]
But, it's still not working in ion-list, even with `item-content` attribute and the following CSS:

```
.overflow {
        contain: none; 
        overflow: visible;
 }
```

**Comment by ar27111994** [comment]
ok, my mistake, I was including `ion-item` alongside `item-content` attribute. Now, the only mystery that remains is that why wasn't it working with the previous service code. Anyways, I'm closing this issue, as I have found a workaround, you can look around and find the actual problem if there is one, while using my my code.
