### ISSUE TITLE
Can't provide array as data source

### ISSUE THREAD

**Issue by lakehouseru** [kadoshms/ionic2-autocomplete#144]
There's a statement in a docs

> 1. A simple function that returns an Array of items

But there's no example of code explaining how to do it.  Can anyone give an example code? 

As I can see [dataProvider]="only Provider Class here" can receive only Service inherited from AutoCompleteService.

**Comment by kadoshms** [comment]
You can simply create a function that returns an array, and pass it as a dataProvider
