### ISSUE TITLE
Display other attributes.

### ISSUE THREAD

**Issue by craidencool13** [kadoshms/ionic2-autocomplete#146]
Can I display another attribute to the dropdown list?

Sample:
`<ng-template #withFlags let-attrs="attrs" class="search-preview">
    <span [innerHTML]="attrs.name| boldprefix:attrs.keyword"></span>
     <span [innerHTML]="attrs.address | boldprefix:attrs.keyword"></span>
</ng-template>`

Thanks!

**Comment by kadoshms** [comment]
@craidencool13 sure, you can access the `attrs.data` within the template, and it has access to all the data attributes associated with your items.
