### ISSUE TITLE
Not rendering in ion-item and ion-slide

### ISSUE THREAD

**Issue by mpadmaraj** [kadoshms/ionic2-autocomplete#147]
I was trying to use this with-in ion-item that is with-in ion-slide but it was not showing the autocomplete component. Is there something I can tweak to make this work?

**Comment by kadoshms** [comment]
@mpadmaraj Please look at https://github.com/kadoshms/ionic2-autocomplete/issues/95 and https://github.com/kadoshms/ionic2-autocomplete/issues/104
