### ISSUE TITLE
  Module '".../ionic2-auto-complete/dist/index"' has no exported member 'AutoCompleteItemComponent'.

### ISSUE THREAD

**Issue by jddev14** [kadoshms/ionic2-autocomplete#15]
i seem to keep getting this error, is am i doing anything wrong?
      Module '"C:/Users/JonathanD/shoppy_v0.0.2/node_modules/ionic2-auto-complete/dist/index"' has no exported
            member 'AutoCompleteItem'.

       L1:  import { AutoCompleteItem ,AutoCompleteItemComponent ,AUTOCOMPLETE_PIPES} from 'ionic2-auto-complete';

            Module '"C:/Users/JonathanD/shoppy_v0.0.2/node_modules/ionic2-auto-complete/dist/index"' has no exported
            member 'AutoCompleteItemComponent'.

       L1:  import { AutoCompleteItem ,AutoCompleteItemComponent ,AUTOCOMPLETE_PIPES} from 'ionic2-auto-complete';

**Comment by kadoshms** [comment]
Please check in the new version.

**Comment by sanutv** [comment]
Can you please share the latest version number?

**Comment by kadoshms** [comment]
1.5.2-beta
