### ISSUE TITLE
Set initial value

### ISSUE THREAD

**Issue by luckyboy07** [kadoshms/ionic2-autocomplete#16]
can we set initial value? if yes, can you give us an example? thanks

**Comment by kadoshms** [comment]
Changed in f670bb26aaba21dd12dc91c22f7d88b7169bbc1c

You can now inject an initial value, by binding [keyword]:

`  <ion-auto-complete [dataProvider]="autoCompleteService" [keyword]="'some value'" (itemSelected)="getVal($event)" [options]="{ placeholder: 'type a country name' }"></ion-auto-complete>
`
