### ISSUE TITLE
ERROR TypeError: "value.replace is not a function"

### ISSUE THREAD

**Issue by anujsinghwd** [kadoshms/ionic2-autocomplete#164]
![screen shot 2018-08-08 at 12 43 05 am](https://user-images.githubusercontent.com/24680004/43797154-1fa98b00-9aa4-11e8-96eb-593932b74354.png)

**Comment by akashbiz** [comment]
+1, same issue

**Comment by jrquick17** [comment]
https://github.com/kadoshms/ionic2-autocomplete/issues/168#issuecomment-468690027

> `replace()` is a [JavaScript function](https://www.w3schools.com/jsref/jsref_replace.asp) for strings. If the function does not exist then value is not a string. Looking into BoldPrefix it seems that you are not passing a string for the label. Make sure your labelAttribute or the getLabelAttribute are returning strings.
