### ISSUE TITLE
add a licence

### ISSUE THREAD

**Issue by brunosmartin** [kadoshms/ionic2-autocomplete#21]
If it is a free software, I would like to contribute.

**Comment by kadoshms** [comment]
Please feel free to contribute, I'll add the license ASAP

**Comment by brunosmartin** [comment]
Well, to be honest, we already started! ;-) we made some hacks to make it work on angular2 and add some events from ionic's search bar.

https://github.com/virgilio/ionic2-autocomplete/tree/angular2

What about keep a version angular2/ionic2 compatible? I think the code on master branch works fine on angular2, but we have changed package.json to install on ionic2 app.

**Comment by mosca90** [comment]
@brunosmartin what the difference between this and yours version? 👍

**Comment by kadoshms** [comment]
Added license
