### ISSUE TITLE
Search results not visible

### ISSUE THREAD

**Issue by cocowalla** [kadoshms/ionic2-autocomplete#23]
I've configured things as in the readme, and have getResults returning a static array of objects for testing.

However, the search results are not being displayed. I don't see any errors in the console logs.

Any idea what could be wrong here?

**Comment by kadoshms** [comment]
Can you please provide some more information?
Maybe your service and component code?

**Comment by cocowalla** [comment]
Sure. The service:

```
@Injectable()
export class MySearchService implements AutoCompleteService {
	labelAttribute = "name";

	getResults(keyword: string): any {
		let myObjects: MyType[] = [];
		
		let myObject1 = <MyType> {
			name: "Test",
			value: 2323
		};

		let myObject2 = <MyType> {
			name: "Test2",
			value: 4343
		};

		myObjects.push(myObject1);
		myObjects.push(myObject2);
		
		return myObjects;
	}
}
```
Which is injected into the ctor of the component:

```
public constructor(private searchService: MySearchService) {
...
```
And finally how it's used in HTML:
```
<ion-auto-complete [dataProvider]="searchService" [options]="{ placeholder : 'Search' }"></ion-auto-complete>
```

If it helps, I'm on Ionic 3 with Angular 4. Everything builds OK for Android, so no Typescript syntax issues.

**Comment by kadoshms** [comment]
Using Ionic 3 and Angular 4 as well, but everything seems to work fine (I used your code):

![screenshot from 2017-04-25 17 00 59](https://cloud.githubusercontent.com/assets/5352933/25389369/0f3edda2-29d9-11e7-8ad6-52988f0ace07.png)

**Comment by cocowalla** [comment]
Weird. I've gone over it several times and everything _seems_ to be correct, but I must be missing something.

I've gone ahead and implemented my own solution, but I'll give this another try next time I need auto complete functionality.

**Comment by kadoshms** [comment]
@cocowalla please contact me for further assistance kadoshms@gmail.com, I am curious about your problem.
