### ISSUE TITLE
what if i dont wanna use labelAttribute ?

### ISSUE THREAD

**Issue by rkmahale17** [kadoshms/ionic2-autocomplete#24]
{
    "response_code": 200,
    "total": 23,
    "train": [
        "SHARAVATHI EXP (11035)",
        "SHARAVATI  EXP (11036)",
        "SHAKTIPUNJ EXP (11447)",
        "SHAKTIPUNJ EXP (11448)",
        "SHANE PUNJAB (12497)",
        "SHANE PUNJAB (12498)",
        "SHALIMAR EXP (14645)",
        "SHALIMAR EXP (14646)",
        "SHAHEED EXPRESS (14673)",
        "SHAHEED EXP (14674)",
        "SHALIMAR EXP (22641)",
        "SHATABDI EXP (12007)",
        "SHATABDI EXP (12008)",
        "SHATABDI EXP (12009)",
        "SHATABDI EXP (12010)",
        "SHATABDI EXPRES (12019)",
        "SHATABDI EXPRES (12020)",
        "SHATABDI EXP (12025)",
        "SHATABDI EXP (12027)",
        "SHATABDI EXP (12028)",
        "SHATABDI EXPRES (12041)",
        "SHATABDI EXP (12243)",
        "SHATABDI EXP (12244)"
    ],
    "trains": [
        {
            "name": "SHARAVATHI EXP",
            "number": "11035"
        },
        {
            "name": "SHARAVATI  EXP",
            "number": "11036"
        },
        {
            "name": "SHAKTIPUNJ EXP",
            "number": "11447"
        },
        {
            "name": "SHAKTIPUNJ EXP",
            "number": "11448"
        },
        {
            "name": "SHANE PUNJAB",
            "number": "12497"
        },
        {
            "name": "SHANE PUNJAB",
            "number": "12498"
        },
        {
            "name": "SHALIMAR EXP",
            "number": "14645"
        },
        {
            "name": "SHALIMAR EXP",
            "number": "14646"
        },
        {
            "name": "SHAHEED EXPRESS",
            "number": "14673"
        },
        {
            "name": "SHAHEED EXP",
            "number": "14674"
        },
        {
            "name": "SHALIMAR EXP",
            "number": "22641"
        },
        {
            "name": "SHATABDI EXP",
            "number": "12007"
        },
        {
            "name": "SHATABDI EXP",
            "number": "12008"
        },
        {
            "name": "SHATABDI EXP",
            "number": "12009"
        },
        {
            "name": "SHATABDI EXP",
            "number": "12010"
        },
        {
            "name": "SHATABDI EXPRES",
            "number": "12019"
        },
        {
            "name": "SHATABDI EXPRES",
            "number": "12020"
        },
        {
            "name": "SHATABDI EXP",
            "number": "12025"
        },
        {
            "name": "SHATABDI EXP",
            "number": "12027"
        },
        {
            "name": "SHATABDI EXP",
            "number": "12028"
        },
        {
            "name": "SHATABDI EXPRES",
            "number": "12041"
        },
        {
            "name": "SHATABDI EXP",
            "number": "12243"
        },
        {
            "name": "SHATABDI EXP",
            "number": "12244"
        }
    ]
}

this my array and i want to access TRAIN array not train then i dont want use labelAttribute any more
    return result.json().train
         
            .filter(item => item..toLowerCase().startsWith(keyword.toLowerCase()) ) 
           it is giving me cant replace 

    return result.json().trains
         
            .filter(item => item.name.toLowerCase().startsWith(keyword.toLowerCase()) ) 
           this code give me output but it is TRAINS arry not TRAIN

**Comment by kadoshms** [comment]
Fixed in [f8cb7f529fda4f2e4fcb24fc500dedc1dbeaf6fe](https://github.com/kadoshms/ionic2-autocomplete/commit/f8cb7f529fda4f2e4fcb24fc500dedc1dbeaf6fe).

(new version will be uploaded soon)
