### ISSUE TITLE
Template parse error!!

### ISSUE THREAD

**Issue by asapping99** [kadoshms/ionic2-autocomplete#25]
![image](https://cloud.githubusercontent.com/assets/10718850/25472797/ceae32b6-2b67-11e7-8a83-2b917accfc6b.png)

You must remove the value attribute from 'ion-searchbar'.

**Comment by kadoshms** [comment]
How can I reproduce this issue?

**Comment by iSURUAVISHKA** [comment]
I am having same problem. "Template parse errors"

**Comment by kadoshms** [comment]
Please share the output of your ionic info

**Comment by iSURUAVISHKA** [comment]
![ceae32b6-2b67-11e7-8a83-2b917accfc6b](https://cloud.githubusercontent.com/assets/20269703/25574515/cadf0ebe-2e6c-11e7-9b76-9aaa00ac8755.png)

**Comment by iSURUAVISHKA** [comment]
![untitled](https://cloud.githubusercontent.com/assets/20269703/25574673/21502db8-2e6e-11e7-96eb-010a4d605f37.jpg)

**Comment by kadoshms** [comment]
[0f17c9acd0ae4cd8c6a772b5513720c8222d33e4](https://github.com/kadoshms/ionic2-autocomplete/commit/0f17c9acd0ae4cd8c6a772b5513720c8222d33e4)
I removed the [value] binding in rc2 (please uninstall the plugin and re-install `npm install --save ionic2-auto-complete@1.4.2-rc2`).

If you want to set a default value, please refer to https://github.com/kadoshms/ionic2-autocomplete/issues/16

Let me know if that helped.

**Comment by iSURUAVISHKA** [comment]
It works. Thank you for you help!!!
