### ISSUE TITLE
templateUrl can't find html page

### ISSUE THREAD

**Issue by mosca90** [kadoshms/ionic2-autocomplete#27]
Custom template.
**comp-test-item.ts file:**
```
import {AutoCompleteItem, AutoCompleteItemComponent} from 'ionic2-auto-complete';
@AutoCompleteItem({
  templateUrl: 'comp-test-item.html'
})
export class CompTestItem extends AutoCompleteItemComponent{}
```
**comp-test-item.html**
`test: <span [innerHTML]="data.name| boldprefix:keyword"></span>`

Give this error:
GET http://172.16.0.167:8100/comp-test-item.html 404 (Not Found)
Unhandled Promise rejection: Failed to load comp-test-item.html ; Zone: <root> ; Task: Promise.then ; Value: Failed to load comp-test-item.html undefined

Which address the plugin expects?

**Comment by kadoshms** [comment]
Currently `templateUrl` is not supported (use template instead)
 Updating the docs.
Thanks for your assitance!
