### ISSUE TITLE
Installation issue

### ISSUE THREAD

**Issue by sguddati** [kadoshms/ionic2-autocomplete#29]
When I install ionic2-autocomplete with npm, and do the ionic serve, getting following issue. Any suggestion please?? I am relatively new to ionic2.
------------------

[01:58:08]  typescript: ...omplete/node_modules/ionic-angular/components/virtual-scroll/virtual-scroll.d.ts, line: 220
            Type 'IterableDiffer' is not generic.

     L219:  private _dom;
     L220:  _differ: IterableDiffer<any>;
     L221:  _scrollSub: any;

[01:58:08]  transpile failed

-------------
Below is ionic info

Your system information:

Cordova CLI: 6.5.0
Ionic Framework Version: 2.2.0
Ionic CLI Version: 2.2.3
Ionic App Lib Version: 2.2.1
Ionic App Scripts Version: 1.1.4
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Windows 10
Node Version: v6.10.2
Xcode version: Not installed

**Comment by kadoshms** [comment]
What version of TypeScript do you have installed on your system?
Please also share your `ionic info` output.

**Comment by sguddati** [comment]
Below is the ionic info

----------
Cordova CLI: 6.5.0
Ionic Framework Version: 2.2.0
Ionic CLI Version: 2.2.3
Ionic App Lib Version: 2.2.1
Ionic App Scripts Version: 1.1.4
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Windows 10
Node Version: v6.10.2
Xcode version: Not installed
----------------------
package.json is as below

{
  "name": "Test",
  "author": "Test",
  "homepage": "http://www.myserver.com",
  "private": true,
  "scripts": {
    "ionic:build": "ionic-app-scripts build",
    "ionic:serve": "ionic-app-scripts serve"
  },
  "dependencies": {
    "@angular/common": "2.4.8",
    "@angular/compiler": "2.4.8",
    "@angular/compiler-cli": "2.4.8",
    "@angular/core": "2.4.8",
    "@angular/forms": "2.4.8",
    "@angular/http": "2.4.8",
    "@angular/platform-browser": "2.4.8",
    "@angular/platform-browser-dynamic": "2.4.8",
    "@angular/platform-server": "2.4.8",
    "@ionic/storage": "2.0.0",
    "@types/googlemaps": "^3.25.38",
    "bourbon": "^4.2.7",
    "ionic-angular": "2.2.0",
    "ionic-native": "2.4.1",
    "ionic2-auto-complete": "^1.4.2-rc0",
    "ionicons": "3.0.0",
    "rxjs": "5.0.1",
    "sw-toolbox": "3.4.0",
    "typescript": "^2.3.2",
    "zone.js": "0.7.2"
  },
  "devDependencies": {
    "@ionic/app-scripts": "1.1.4",
    "angular-ide": "^0.9.19",
    "typescript": "2.0.9"
  },
  "cordovaPlugins": [
    "cordova-plugin-device",
    "cordova-plugin-console",
    "cordova-plugin-whitelist",
    "cordova-plugin-splashscreen",
    "cordova-plugin-statusbar",
    "ionic-plugin-keyboard",
    "cordova-plugin-nativestorage",
    "cordova-plugin-inappbrowser",
    "cordova-plugin-x-socialsharing",
    {
      "locator": "https://github.com/Rohfosho/CordovaCallNumberPlugin.git",
      "id": "call-number"
    },
    "cordova-plugin-geolocation",
    {
      "id": "cordova-plugin-facebook4",
      "locator": "cordova-plugin-facebook4",
      "variables": {
        "APP_ID": "826720427470540",
        "APP_NAME": "Ion2FullApp"
      }
    },
    {
      "id": "cordova-plugin-googleplus",
      "locator": "cordova-plugin-googleplus",
      "variables": {
        "REVERSED_CLIENT_ID": "com.googleusercontent.apps.1001905109734-c6ime9d783l15kjmi2pqsplku4vua2e5"
      }
    }
  ],
  "cordovaPlatforms": [
    {
      "platform": "ios",
      "version": "~4.1.1",
      "locator": "ios"
    },
    {
      "platform": "android",
      "version": "~5.1.1",
      "locator": "android"
    }
  ],
  "description": "Test",
  "config": {
    "ionic_sass": "./config/sass.config.js"
  }
}

**Comment by sguddati** [comment]
Below is the ionic info
Cordova CLI: 6.5.0
Ionic Framework Version: 2.2.0
Ionic CLI Version: 2.2.3
Ionic App Lib Version: 2.2.1
Ionic App Scripts Version: 1.1.4
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Windows 10
Node Version: v6.10.2
Xcode version: Not installed
package.json is as below{
"name": "Test",
"author": "Test",
"homepage": "http://www.myserver.com",
"private": true,
"scripts": {
"ionic:build": "ionic-app-scripts build",
"ionic:serve": "ionic-app-scripts serve"
},
"dependencies": {
"@angular/common": "2.4.8",
"@angular/compiler": "2.4.8",
"@angular/compiler-cli": "2.4.8",
"@angular/core": "2.4.8",
"@angular/forms": "2.4.8",
"@angular/http": "2.4.8",
"@angular/platform-browser": "2.4.8",
"@angular/platform-browser-dynamic": "2.4.8",
"@angular/platform-server": "2.4.8",
"@ionic/storage": "2.0.0",
"@types/googlemaps": "^3.25.38",
"bourbon": "^4.2.7",
"ionic-angular": "2.2.0",
"ionic-native": "2.4.1",
"ionic2-auto-complete": "^1.4.2-rc0",
"ionicons": "3.0.0",
"rxjs": "5.0.1",
"sw-toolbox": "3.4.0",
"typescript": "^2.3.2",
"zone.js": "0.7.2"
},
"devDependencies": {
"@ionic/app-scripts": "1.1.4",
"angular-ide": "^0.9.19",
"typescript": "2.0.9"
},
"cordovaPlugins": [
"cordova-plugin-device",
"cordova-plugin-console",
"cordova-plugin-whitelist",
"cordova-plugin-splashscreen",
"cordova-plugin-statusbar",
"ionic-plugin-keyboard",
"cordova-plugin-nativestorage",
"cordova-plugin-inappbrowser",
"cordova-plugin-x-socialsharing",
{
"locator": "https://github.com/Rohfosho/CordovaCallNumberPlugin.git",
"id": "call-number"
},
"cordova-plugin-geolocation",
{
"id": "cordova-plugin-facebook4",
"locator": "cordova-plugin-facebook4",
"variables": {
"APP_ID": "826720427470540",
"APP_NAME": "Ion2FullApp"
}
},
{
"id": "cordova-plugin-googleplus",
"locator": "cordova-plugin-googleplus",
"variables": {
"REVERSED_CLIENT_ID": "com.googleusercontent.apps.1001905109734-c6ime9d783l15kjmi2pqsplku4vua2e5"
}
}
],
"cordovaPlatforms": [
{
"platform": "ios",
"version": "~4.1.1",
"locator": "ios"
},
{
"platform": "android",
"version": "~5.1.1",
"locator": "android"
}
],
"description": "Test",
"config": {
"ionic_sass": "./config/sass.config.js"
}
}

**Comment by kadoshms** [comment]
Ok, it seems like your Ionic version is far behind, but let's see if my latest commit helps.
commit 33b2f3ab8b951675f9d0d11f1dd631531091c3e8

Please uninstall and install rc1 instead:
`npm uninstall --save ionic2-auto-complete`

And then:
`npm install --save ionic2-auto-complete@1.4.2-rc1`

**Comment by sguddati** [comment]
it worked .. thank you .. 
Srinivas.

**Comment by sguddati** [comment]
Any way to associate this auto complete to a input/select field instead of searchbar?
Srinivas.

**Comment by kadoshms** [comment]
@sguddati no, the all point of this plugin is that it based on this component :)
I believe that there are other similar plugins, that are not neccessarly based on ionic.

**Comment by sguddati** [comment]
Any suggestions on a good plugin for this purpose? I am trying to make ion-input field to be having the auto complete
Srinivas

**Comment by kadoshms** [comment]
I'd suggest you to fork this repository and simply change the component. should be easy. your'e welcome to ask me questions

**Comment by sguddati** [comment]
Tried doing it and not able to get it working. Ending up with lot of issues in controlling the layout. 
Can I request you to create a version of this that has support for <ion-input>?
Rest of my form is having fields like below with floating labels. 
           <ion-item>         <ion-label floating>{{options.placeholder}}</ion-label>         <ion-input formControlName="country"></ion-input>     </ion-item>
Srinivas      From: Mor Kadosh <notifications@github.com>
 To: kadoshms/ionic2-autocomplete <ionic2-autocomplete@noreply.github.com> 
Cc: sguddati <sguddati@yahoo.com>; Mention <mention@noreply.github.com>
 Sent: Tuesday, May 2, 2017 6:45 AM
 Subject: Re: [kadoshms/ionic2-autocomplete] Installation issue (#29)
   
I'd suggest you to fork this repository and simply change the component. should be easy. your'e welcome to ask me questions—

**Comment by sguddati** [comment]
After some struggle got it working.  But the styles are not working in safari or ios smartphone. Same code is working on chrome. It is happening with searchbar component that you provided with no changes. I will open another issue to avoid any confusion
