### ISSUE TITLE
Showing all results when using static data.

### ISSUE THREAD

**Issue by lukealford** [kadoshms/ionic2-autocomplete#3]
So i'm just using this as a quick way of not making people type out a whole item as we know most of the categories they want to search so we are opting to use static data.

My Service is the following, I may be using it wrong I'm not sure since you didn't show how a static example would work in the docs.

```
import {AutoCompleteService} from 'ionic2-auto-complete';
import { Http } from '@angular/http';
import {Injectable} from "@angular/core";

@Injectable(

)

export class CompleteService implements AutoCompleteService {
  labelAttribute = "item";
  results: any;
  constructor(private http:Http) {

  }
  getResults(keyword:string) {
    return this.results = [
      {item:'engine oil'},
      {item:'engine oil filter'},
      {item:'fuel filter'},
      {item:'air cleaner'},
      {item:'hydraulic oil'},
      {item:'hydraulic oil filter'},
      {item:'transmission oil'},
      {item:'transmission oil filter'},
      {item:'coolant'},
      {item:'cab filter'},
      {item:'battery'},
      {item:'tires'}
    ]
  }
}

```
And here is a screenshot of the issue.
![bug](https://cloud.githubusercontent.com/assets/679094/18225626/7259cafc-723a-11e6-89b9-9eea86dfe3bd.png)

**Comment by kadoshms** [comment]
Thanks for letting me know, I'll check this out as soon as I come back from vacation :)
