### ISSUE TITLE
Feature request: add an option to use `ion-input` instead of `ion-searchbar`

### ISSUE THREAD

**Issue by sguddati** [kadoshms/ionic2-autocomplete#30]
When the user types in values in search text, drop down values are not appearing in Safari or iPhone. Same app is working fine on Chrome. Looks like the styles are not working in iOS based browsers. Can you verify please?

**Comment by kadoshms** [comment]
I can't confirm this issue, Iv'e  just tested with iOS emulator (to be more specfic I used iPad-Air, ios 10.1) and it worked just fine. 
Also tested in Safari and it worked as well :)

Did you validate your data provider?

**Comment by sguddati** [comment]
I am able to see the data with Chrome, but not with Safari. I will check again.

**Comment by sguddati** [comment]
I can confirm that it is not the issue with the component. It is working with local data and not with remote provider call. But interestingly the remote call is working in chrome, but not in safari. Something to do with CORs in safari, I believe that is not fetching the data. Thanks for your help. 
As I requested before, if you can create ion-input component, it will be a great addition. For now, I am able to move on with locally changing the component for my needs. 
Srinivas.

**Comment by kadoshms** [comment]
I will add this feature to the next release!

**Comment by kadoshms** [comment]
added to `1.5.0-beta` a55e300b3d1b2e5a71273fccb7262fc5ad644933
