### ISSUE TITLE
Use different AutoCompleteItem

### ISSUE THREAD

**Issue by MonsieurMan** [kadoshms/ionic2-autocomplete#31]
If I understand it right, as of know we can only customize one AutoCompleteItem and have to use it for all the AutoComplete component ?
Or is there a way to create multiple items and use them for different AutoComplete component ?
If not I'd like to work on the feature.

**Comment by kadoshms** [comment]
You are totally right. As for now (and by design) it is only possible to have a single template.

You are VERY welcome to work on it :)

**Comment by MonsieurMan** [comment]
I managed to change the item with a custom directive.
As of now the usage is :
`<ion-auto-complete [autoCompleteItem]="itemComponent"></ion-auto-complete>`

There's a few things I'm not happy with so it's not pushed on my fork yet.
I'll keep you updated by this weekend.

**Comment by MonsieurMan** [comment]
After hours of struggle I think it won't be possible.
The problem is that Ionic uses AOT compilation that makes it impossible to dynamically load a component.

**Comment by kadoshms** [comment]
Thanks for your attempt!
you are very welcome to contfibute in fhe future :)

**Comment by kadoshms** [comment]
@MonsieurMan I am happy to tell you that Iv'e found a good solution to this scenario, using `ngTemplateOutlet`. 
I will release this feature on the upcominfg `1.5.0` :)
