### ISSUE TITLE
[Question] Move searchbar cursor to the end of the line on focus 

### ISSUE THREAD

**Issue by snpefk** [kadoshms/ionic2-autocomplete#35]
Hi, thx for your component. 

Can you help me figure out how i can move carret to the end of the searchbar input? I can't find answers in the component or official docs.

**Comment by kadoshms** [comment]
I am sorry but I'm not sure I understand your question :)
Are you talking about the cancel button?

**Comment by snpefk** [comment]
I'm talking about cursor. Sorry to mislead you. 
![text_cursor_blinking_larger](https://cloud.githubusercontent.com/assets/2883201/25838082/7352df5e-34bb-11e7-88ef-dfac8e7fcfa9.gif)

I want the cursor move to the end of keyword string on searchbar focus. 
Now you understand?

**Comment by kadoshms** [comment]
Hey, 
Unfortunately, this component relies on the ionic's `ion-searchbar` component, which has no such feature out of the box.
I will consider to find a proper solution for this issue in the next release.

Thanks for your feedback!
