### ISSUE TITLE
RC0 issue

### ISSUE THREAD

**Issue by arsewizz** [kadoshms/ionic2-autocomplete#4]
hey, thirst thanks for the super work. with the latest update ionic doesn't use gulp, what next?

**Comment by kadoshms** [comment]
Your'e totally right, I should figure it out.
Ill probably work on it tommorow!

**Comment by arsewizz** [comment]
okey thanks, just wainting for

**Comment by kadoshms** [comment]
Seems like upgrading to RC.0 requires more work than I though (since they also upgraded Angular), but look forward for my updates!

**Comment by arsewizz** [comment]
i'm waiting

**Comment by kadoshms** [comment]
I updated the plugin and the docs, enjoy!
