### ISSUE TITLE
Feature request: When a user initially clicks on the searchbar, the autocomplete displays all possible options.

### ISSUE THREAD

**Issue by KyleMcNutt** [kadoshms/ionic2-autocomplete#40]
For scenarios where you don't have _that_ many options it's actually useful to be able to see the different options before you input, so you know the options that are hopefully going to return _some_ results.

I believe that right now this if check:
https://github.com/kadoshms/ionic2-autocomplete/blob/master/src/autocomplete.component.ts#L77

Would prevent that because the keyword is empty on initial click.

Thoughts on adding this kind of feature? Most likely behind some option flag?

**Comment by kadoshms** [comment]
Yes, why not, I can totally add this feature soon.

**Comment by kadoshms** [comment]
Added (4884ce0da0174047beb15f20a16861b023305bad)
