### ISSUE TITLE
getting syntax error when running in emulator

### ISSUE THREAD

**Issue by cwang2002** [kadoshms/ionic2-autocomplete#41]
![screenshot from 2017-05-14 11 17 37](https://cloud.githubusercontent.com/assets/5000750/26070928/611b2f40-3974-11e7-98d8-6c4dbded1481.png)
Is this because you have compile target to ES6?

**Comment by kadoshms** [comment]
@cwang2002 I am not sure what I am looking at :eyes: 
How are you running your project?

**Comment by cwang2002** [comment]
I was running it in android emulator and use chrome inspector to debug the issue. the main.js has ES6 syntax in it.
The code works fine with ionic serve and on my nexus 6 device, just the emulator having the issue.

**Comment by kadoshms** [comment]
I am not sure what causes that..
can you please try to compile to es5 and let me know if that works?

**Comment by kadoshms** [comment]
This does not reproduce on `1.5.0-beta`. I did change the compile target to es5, it might be the reason.
