### ISSUE TITLE
How to call function after data is selected ?

### ISSUE THREAD

**Issue by rkmahale17** [kadoshms/ionic2-autocomplete#42]

**Comment by kadoshms** [comment]
As described in the docs, you can bind the `itemSelected` event to the component.
Example:

`<ion-auto-complete [itemSelected]="doSomething($event)" ..... ></ion-auto-complete>`

**Comment by rkmahale17** [comment]
I tired that solution but it's giving me error....

polyfills.js:3 Unhandled Promise rejection: Template parse errors:
Can't bind to 'itemSelected' since it isn't a known property of 'ion-auto-complete'.
1. If 'ion-auto-complete' is an Angular component and it has 'itemSelected' input, then verify that it is part of this module.
2. If 'ion-auto-complete' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message.
3. To allow any property add 'NO_ERRORS_SCHEMA' to the '@NgModule.schemas' of this component. ("
<ion-content class="has-header">
  <br>
  <ion-auto-complete [dataProvider]="autoForSeat" [ERROR ->][itemSelected]="ionicViewData($event)"  #searchbar ></ion-auto-complete>

**Comment by kadoshms** [comment]
Please post your code

**Comment by rkmahale17** [comment]
1. seat.html
2. <ion-header>
3. <ion-navbar color="primary">
4. <button menuToggle>
5. <ion-icon name="menu"></ion-icon>
6. </button>
7. <ion-title>
8. Seat Availability
9. </ion-title>
10. </ion-navbar>
11. </ion-header>
12. 
13. <ion-content class="has-header">
14. <br>
15. <ion-auto-complete [dataProvider]="autoForSeat" [itemSelected]="ionicViewData($event)"  #searchbar ></ion-auto-complete>
16. 
17. 
18. <ion-list>
19. 
20. <ion-item>
21. 
22. <ion-select interface="popover" >
23. <ion-label>Source</ion-label>
24. <ion-option [value] = "p.fullname"  *ngFor="let p of rlwy.trainRoute">{{p.fullname}}</ion-option>
25. 
26. </ion-select>
27. </ion-item>
28. 
29. </ion-list>
30. 
31. <div padding style="text-align: center;">
32. 
33. 
34. <button ion-button round outline (click)="ionicViewData()">Get Status</button>
35. 
36. </div>
37.  seat.ts

1. import { Component, ViewChild, ElementRef } from '@angular/core';
2. import { NavController, Platform } from 'ionic-angular';
3. import { railwayService } from '../../services/rlwyServices';
4. import { autoForSeat } from '../../services/autoForSeat';
5. import {AutoCompleteComponent} from "ionic2-auto-complete/dist";
6. import { Geolocation } from '@ionic-native/geolocation';
7. import {trainStatus} from '../../pages/trainStatus/trainStatus';
12. declare var google;
13. 
14. @Component({
15. selector: 'seat',
16. templateUrl: 'seat.html',
17. 
18. })
19. 
20. export class seat {
21. 
22. @ViewChild('map') mapElement: ElementRef;
23. map: any;
24. searchVal: string;
25. railValue:any;
26. @ViewChild('searchbar')
27. searchbar: AutoCompleteComponent;
28. constructor(public navCtr:NavController , public rlwy: railwayService,public autoForSeat: autoForSeat, 
29. public geolocation: Geolocation ){
30. 
31. 
32. 
33. }
34. 
35. ionicViewData(){
36. this.searchVal =this.searchbar.getValue();
37. var numb = this.searchVal.match(/\d/g);
38. var sham = numb.join("");
39. this.rlwy.getRoute(sham);
40. //console.log(this.completeTestService.searchbar );
41. 
42. }
43. 
44. 
45. 
46. }
47. Mine code running fine for autocomplete and other thing ...i just want to call a fucntion after selection. I tried it with [itemSelected]="ionicViewData($event)" and also for [itemSelected]="ionicViewData()"
48. 
49. 

38.

**Comment by rkmahale17** [comment]
seat.js

import { Component, ViewChild, ElementRef } from '@angular/core';
import { NavController, Platform } from 'ionic-angular';
import { railwayService } from '../../services/rlwyServices';
import { autoForSeat } from '../../services/autoForSeat';
import {AutoCompleteComponent} from "ionic2-auto-complete/dist";
import { Geolocation } from '@ionic-native/geolocation';
import {trainStatus} from '../../pages/trainStatus/trainStatus';


declare var google;

@Component({
  selector: 'seat',
  templateUrl: 'seat.html',

})

export class seat {
    
           @ViewChild('map') mapElement: ElementRef;
  map: any;
  searchVal: string;
 railValue:any;
    @ViewChild('searchbar')
  searchbar: AutoCompleteComponent;
constructor(public navCtr:NavController , public rlwy: railwayService,public autoForSeat: autoForSeat, 
public geolocation: Geolocation ){



  }
 
ionicViewData(){
this.searchVal =this.searchbar.getValue();
var numb = this.searchVal.match(/\d/g);
var sham = numb.join("");
this.rlwy.getRoute(sham);
 //console.log(this.completeTestService.searchbar );
  
}



}


seat.html

  <ion-auto-complete [dataProvider]="autoForSeat" [ionInput]="ionicViewData()"  #searchbar ></ion-auto-complete>

**Comment by kadoshms** [comment]
what version of the plugin are you using?

**Comment by kadoshms** [comment]
@rkmahale17 I would first recommend you to upgrade the plugin (1.5.0-beta  is available).

Secondly, I you should bind the event this way (I edited my previous post):
`<ion-auto-complete (itemSelected)="doSomething($event)" ..... ></ion-auto-complete>`

I by mistake confused between the two ways of binding ( it should be '()' and not '[]')
