### ISSUE TITLE
searching indication while getting the search results

### ISSUE THREAD

**Issue by dd-here** [kadoshms/ionic2-autocomplete#44]
show a searching indication while the search api returns the result set.

Do we have any option to show such indication

**Comment by kamok** [comment]
@dd-here You can put a loading https://ionicframework.com/docs/api/components/loading/LoadingController/ 
inside the `ionAutoInput` callback. I don't know why you'd need a loading screen since your server shouldn't be that slow. 

This is not an enhancement that's needed imo.

**Comment by kadoshms** [comment]
@kamok I totally agree with you.
