### ISSUE TITLE
Using ion-auto-complete two times one is not working

### ISSUE THREAD

**Issue by rkmahale17** [kadoshms/ionic2-autocomplete#47]
<ion-auto-complete [dataProvider]="stationAuto"  (itemSelected)="ionicViewData($event)" #searchbar></ion-auto-complete>
  <ion-auto-complete [dataProvider]="stationAuto" (itemSelected)="ionicViewData1($event)" #searchbar></ion-auto-complete>
  
i call two ion-complete for selecting source and destination. Autocomplete list is comming for both but things is secound declare ion-complte cause keyword to null or i will like of 1st ion-complete keyword.
ionicViewData(){
   this.from=this.searchbar.getValue(); ///value is comming 
   console.log(this.from);
   this.stNameToCode.getPosts(this.to);
}

ionicViewData1(){
   this.to =this.searchbar.getValue(); //////here value is comming nulll
   console.log(this.to);
   this.stNameToCode.getPosts(this.to);
}

**Comment by kadoshms** [comment]
You are referencing two objects with the same reference (you used #searchbar for both components).
Anyway, the first argument of the itemSelected event is the selected item, which means that you can skip this viewchild refernece and simply do something similar to this:
```

ionicViewData(from){
this.from=from;
console.log(this.from);
this.stNameToCode.getPosts(this.to);
}
```

**Comment by rkmahale17** [comment]
I use  this................
ionicViewData(from){
     this.from=from;
     console.log(this.from);
     this.stNameToCode.getPosts(this.form);
}
in form only $event is getting which is [object object]
and apply this thing for secound ion-auto-complete ....

**Comment by kadoshms** [comment]
This objectct is the object associated with the selected item.
You can console.log it and see how to access the data you need.

**Comment by rkmahale17** [comment]
Are you saying this is json like structure data............in which i have to extract data
ionicViewData(from){
     this.to = from;
        console.log( from  +"##########")
  //  this.stNameToCode.getPosts(this.from);

 
 //console.log(this.completeTestService.searchbar );
  
}

but, man i should know, whats the key to extract like
For Example:-
 "route": [
        {
            "no": 1,
            "station_": {
                "name": "CHANDIGARH",
                "code": "CDG"
            },
            "has_arrived": false,
            "has_departed": true,
            "day": 0,
            "distance": 0,
            "scharr": "Source",
            "schdep": "12:00",
            "actarr": "00:00",
            "actdep": "12:00",
            "scharr_date": "19 Nov 2015",
            "actarr_date": "19 Nov 2015",
            "latemin": 0
        },
in this i know to access the value of route first then other with operator.....
But in this case i dont know from which key i have to take .... i know it array like structed json
Help for same..

**Comment by kadoshms** [comment]
@rkmahale17 I am not sure I understand the issue nor the issue with the plugin.
The auto-complete data provider (in your case stationAuto) is responsible for fetching the data and providing it in a form of an array of elements (could be plain strings, objects, numbers, or whatever you decide). 
The `labelAttribute` in the case of object elements helps the component with displaying the data.
In your case it seems like any element in the list is a station object, which has many properties.
When you use the `selectItem` event, the first argument is always the selected item. In your case again, it is a station object.
Then, you are free to do whatever you will to do with this data.

Please clarify what the issue, so that I can be more helpful.

**Comment by kadoshms** [comment]
Since it is not a plugin related issue, I am closing this for now.
