### ISSUE TITLE
After APK in Tablet its throwing an error

### ISSUE THREAD

**Issue by KrishnaPrasadSS** [kadoshms/ionic2-autocomplete#48]
After APK Installation we are getting below error 
Uncaught SyntaxError: missing ) after argument list
below code is from auto complete.component.ts
if (result instanceof rxjs_1.Observable) {
        result
          .subscribe(
              (results) => {
                this.suggestions = results;
                this.showItemList();
              },
              (error) =>  console.error(error)
          )

**Comment by kadoshms** [comment]
What version of the plugin are you using?

**Comment by KrishnaPrasadSS** [comment]
We are using version number 1.4.2

**Comment by KrishnaPrasadSS** [comment]
To add,  it's working fine in browser but after I covering it to apk it's throwing that error, 
Is this some thing related to es6 to es5 transpile?

**Comment by kadoshms** [comment]
Yes, it is probably it.
can you pleade upgrade to 1.5.0-beta and let me know if that worked?
* just make sure you follow the new readme file

**Comment by kadoshms** [comment]
Yes, it is probably it.
can you pleade upgrade to 1.5.0-beta and let me know if that worked?
* just make sure you follow the new readme file

**Comment by kadoshms** [comment]
Yes, it is probably it.
can you pleade upgrade to 1.5.0-beta and let me know if that worked?
* just make sure you follow the new readme file

**Comment by kadoshms** [comment]
@KrishnaPrasadSS can you confirm?

**Comment by KrishnaPrasadSS** [comment]
Hi sorry for delay,  
I am getting ng-templet  error which upgrade to 1.5.0 beta
Also I tried after adding ng-templet plug in but still getting error

I am planing to keep same version but change target to es5 in tsconfig file

Please share your thoughts and let me know is there any thing else I need to do to get it worked with upgrade version 1.5.0 beta

**Comment by kadoshms** [comment]
Maybe your angular version is out of date? 
Please share your package.json file :)

Anyway, I'd be glad to hear from you how changing the compile target worked for you.

**Comment by KrishnaPrasadSS** [comment]
Hi,
Please find the attached package.json and let me know your thoughts
[package.zip](https://github.com/kadoshms/ionic2-autocomplete/files/1049654/package.zip)

**Comment by kadoshms** [comment]
@KrishnaPrasadSS yes indeed, your angular version is 2.2.1 while the current version supported by the latest ionic version is > 4.0.0.
I should update the docs.
Anyway, do you have any insight about changing the compile target?

**Comment by kadoshms** [comment]
I am closing this for now.
Let me know if this problem occurs in later versions.

**Comment by KrishnaPrasadSS** [comment]
Hi, 
I imported the code into my project instead from node modules it worked and thank you very much for the code and all the hard work. 

I am sure it will work if we changed to es5 as target though I did not tries. 

I used old version 1.4.2 it fulfilled all my reuqirements

Keep rocking

Thanks, 
Krishna
