### ISSUE TITLE
documentClickHandler causing runtime error in browser

### ISSUE THREAD

**Issue by opaltitan** [kadoshms/ionic2-autocomplete#49]
I have only tested this in the browser (with 'ionic serve'), so it's unclear if this issue is present in a built Android/iOS app.

If you click within the browser, then drag the cursor outside of the browser (or even into the address bar or tabs) the app crashes with a runtime error.

I think the following lines of code ('ionic2-auto-complete\index.js'):

>     AutoCompleteComponent.prototype.documentClickHandler = function (event) {
>         var /** @type {?} */ target = event.target;
>         var /** @type {?} */ parent = event.target.parentElement;
>         if (target.className.split(" ").indexOf("ion-auto-complete") == -1 && parent.className.split(" ").indexOf("ion-auto-complete") == -1) {
>             this.hideItemList();
>         }
>     };

need to be updated to this:

>     AutoCompleteComponent.prototype.documentClickHandler = function (event) {
>         var /** @type {?} */ target = event.target;
>         var /** @type {?} */ parent = event.target.parentElement;
>         if (target.className) {
>           if (target.className.split(" ").indexOf("ion-auto-complete") == -1 && parent.className.split(" ").indexOf("ion-auto-complete") == -1) {
>               this.hideItemList();
>           }  
>         }
>     };

Changing to the code above appears to resolve the issue.

**Comment by kadoshms** [comment]
Fixed in 6b012da943ee30ff6126ac96ea1fde4afcac586e
(will be available in the next release)
