### ISSUE TITLE
Would Love to Use for RC0

### ISSUE THREAD

**Issue by queejie** [kadoshms/ionic2-autocomplete#5]
Mor, thanks for your efforts on this.  I'm not yet adept enough to create this component for Ionic2, so I'm hoping you'll finish this one!  Any idea on when it might be ready?

**Comment by kadoshms** [comment]
I am doing my best efforts to fix this asap, alongside my school duties and my job :)
I really hope to have this done very soon, I am currently facing some technical issues, but I will do my best!

**Comment by kadoshms** [comment]
Iv'e updated the plugin and the docs, enjoy!

**Comment by queejie** [comment]
Sorry for the duplication, and thanks again, very much!
