### ISSUE TITLE
labelAttribute function?

### ISSUE THREAD

**Issue by centogram** [kadoshms/ionic2-autocomplete#50]
Is it possible to format the final search string rather than just using a named attribute? 

For example a combination of 2 fields from the resulting object?

**Comment by kadoshms** [comment]
You can always create a custom template, which gives you the ability to fully customize the results.
See the README for more info.

**Comment by centogram** [comment]
Thank you for the quick reply.  Yes, I've noticed the results are fully customizable but the actual search string after selecting a result is what we're trying to customize more than just labelAttribute.  We would like to continue using the entire Object returned when labelAttribute is undefined but also customize the search string query after clicking the result.  For example see the attached image that may help better explain.  

![example](https://user-images.githubusercontent.com/210825/26876790-c1b8b74e-4b55-11e7-8150-91bcd4b374e9.png)

**Comment by centogram** [comment]
I was able to achieve this by doing a .setValue  on the autoCompleteComponent following the itemSelected event.
