### ISSUE TITLE
Using RxJS Subject as a return type of getResults method

### ISSUE THREAD

**Issue by HaithemMosbahi** [kadoshms/ionic2-autocomplete#52]
Hello,

First of all, thank you for this component, well done.
I'm using ionic2-autocomplete in combination with google Places API. I'm doing a call to this api in order to fetch predections for the input entered by the User.
To achieve this, I'm using rxjs Subject which allows me to emit values when the response of the API has been returned. However, the getResults method supports wether to return an Observable or an Array. So here is my question, Can you add support to Subject as the return type of getResults method. Is that possible ?

Thank you.

**Comment by kadoshms** [comment]
Yes I can totally check this out.

**Comment by HaithemMosbahi** [comment]
Ok :) I will create a pull request for this feature
