### ISSUE TITLE
Hi, I'm getting the following error after following your steps. I'm new to ionic and was looking for some help? Cheers

### ISSUE THREAD

**Issue by aussiemarty** [kadoshms/ionic2-autocomplete#54]
Uncaught (in promise): Error: Template parse errors: Can't bind to 'dataProvider' since it isn't a known property of 'ion-auto-complete'. 1. If 'ion-auto-complete' is an Angular component and it has 'dataProvider' input, then verify that it is part of this module. 2. If 'ion-auto-complete' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message. 3. To allow any property add 'NO_ERRORS_SCHEMA' to the '@NgModule.schemas' of this component. (" <ion-row> <ion-col padding> <ion-auto-complete [ERROR ->][dataProvider]="countryAutoProvider"></ion-auto-complete> </ion-col> </ion-row> "): ng:///StudentDetailsFormModule/StudentDetailsForm.html@67:29 'ion-auto-complete' is not a known element: 1. If 'ion-auto-complete' is an Angular component, then verify that it is part of this module. 2. If 'ion-auto-complete' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message. (" <ion-row> <ion-col padding> [ERROR ->]<ion-auto-complete [dataProvider]="countryAutoProvider"></ion-auto-complete> </ion-col> "): ng:///StudentDetailsFormModule/StudentDetailsForm.html@67:10 Error: Template parse errors: Can't bind to 'dataProvider' since it isn't a known property of 'ion-auto-complete'. 1. If 'ion-auto-complete' is an Angular component and it has 'dataProvider' input, then verify that it is part of this module. 2. If 'ion-auto-complete' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message. 3. To allow any property add 'NO_ERRORS_SCHEMA' to the '@NgModule.schemas' of this component. (" <ion-row> <ion-col padding> <ion-auto-complete [ERROR ->][dataProvider]="countryAutoProvider"></ion-auto-complete> </ion-col> </ion-row> "): ng:///StudentDetailsFormModule/StudentDetailsForm.html@67:29 'ion-auto-complete' is not a known element: 1. If 'ion-auto-complete' is an Angular component, then verify that it is part of this module. 2. If 'ion-auto-complete' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message. (" <ion-row> <ion-col padding> [ERROR ->]<ion-auto-complete [dataProvider]="countryAutoProvider"></ion-auto-complete> </ion-col> "): ng:///StudentDetailsFormModule/StudentDetailsForm.html@67:10 at syntaxError (http://localhost:8100/build/main.js:83444:34) at TemplateParser.parse (http://localhost:8100/build/main.js:93935:19) at JitCompiler._compileTemplate (http://localhost:8100/build/main.js:107686:39) at http://localhost:8100/build/main.js:107610:62 at Set.forEach (native) at JitCompiler._compileComponents (http://localhost:8100/build/main.js:107610:19) at createResult (http://localhost:8100/build/main.js:107495:19) at t.invoke (http://localhost:8100/build/polyfills.js:3:8971) at Object.onInvoke (http://localhost:8100/build/main.js:4625:37) at t.invoke (http://localhost:8100/build/polyfills.js:3:8911)Uncaught (in promise): Error: Template parse errors: Can't bind to 'dataProvider' since it isn't a known property of 'ion-auto-complete'. 1. If 'ion-auto-complete' is an Angular component and it has 'dataProvider' input, then verify that it is part of this module. 2. If 'ion-auto-complete' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message. 3. To allow any property add 'NO_ERRORS_SCHEMA' to the '@NgModule.schemas' of this component. (" <ion-row> <ion-col padding> <ion-auto-complete [ERROR ->][dataProvider]="countryAutoProvider"></ion-auto-complete> </ion-col> </ion-row> "): ng:///StudentDetailsFormModule/StudentDetailsForm.html@67:29 'ion-auto-complete' is not a known element: 1. If 'ion-auto-complete' is an Angular component, then verify that it is part of this module. 2. If 'ion-auto-complete' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message. (" <ion-row> <ion-col padding> [ERROR ->]<ion-auto-complete [dataProvider]="countryAutoProvider"></ion-auto-complete> </ion-col> "): ng:///StudentDetailsFormModule/StudentDetailsForm.html@67:10 Error: Template parse errors: Can't bind to 'dataProvider' since it isn't a known property of 'ion-auto-complete'. 1. If 'ion-auto-complete' is an Angular component and it has 'dataProvider' input, then verify that it is part of this module. 2. If 'ion-auto-complete' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message. 3. To allow any property add 'NO_ERRORS_SCHEMA' to the '@NgModule.schemas' of this component. (" <ion-row> <ion-col padding> <ion-auto-complete [ERROR ->][dataProvider]="countryAutoProvider"></ion-auto-complete> </ion-col> </ion-row> "): ng:///StudentDetailsFormModule/StudentDetailsForm.html@67:29 'ion-auto-complete' is not a known element: 1. If 'ion-auto-complete' is an Angular component, then verify that it is part of this module. 2. If 'ion-auto-complete' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message. (" <ion-row> <ion-col padding> [ERROR ->]<ion-auto-complete [dataProvider]="countryAutoProvider"></ion-auto-complete> </ion-col> "): ng:///StudentDetailsFormModule/StudentDetailsForm.html@67:10 at syntaxError (http://localhost:8100/build/main.js:83444:34) at TemplateParser.parse (http://localhost:8100/build/main.js:93935:19) at JitCompiler._compileTemplate (http://localhost:8100/build/main.js:107686:39) at http://localhost:8100/build/main.js:107610:62 at Set.forEach (native) at JitCompiler._compileComponents (http://localhost:8100/build/main.js:107610:19) at createResult (http://localhost:8100/build/main.js:107495:19) at t.invoke (http://localhost:8100/build/polyfills.js:3:8971) at Object.onInvoke (http://localhost:8100/build/main.js:4625:37) at t.invoke (http://localhost:8100/build/polyfills.js:3:8911)

**Comment by kadoshms** [comment]
Did you import the module as specified in the docs?

**Comment by kamok** [comment]
@aussiemarty You should put your logs inside a ` "```" " ```" ` block so it's easier to read.

**Comment by kadoshms** [comment]
Seems like this is not going anywhere...
