### ISSUE TITLE
The drop-down list does not work in the navbar

### ISSUE THREAD

**Issue by squallliu** [kadoshms/ionic2-autocomplete#57]
The drop-down list does not display

**Comment by jjw123** [comment]
Same issue here. Setting overflow: visible on the ion-navbar seems to work on ios, but not on android

**Comment by jjw123** [comment]
setting overflow: visible and contain: none seems to work on both android and ios

**Comment by kadoshms** [comment]
Thanks, I will make efforts to include this fix.

**Comment by kadoshms** [comment]
This problem occurs since the ion-nav-bar does not support overflowing content.
The fix @jjw123 suggested cannot be implemented in the component itself, but the developers using it will have to apply it on their own nav-bars.

Thanks anyway, closing :)

**Comment by FredeHo** [comment]
I fixed it by setting
```
ion-auto-complete {
  ul {
    position: initial;
  }
}
```
