### ISSUE TITLE
How to debounce the getResults function call?

### ISSUE THREAD

**Issue by kamok** [kadoshms/ionic2-autocomplete#59]
My end users are slow typers. I do not want to make 10 calls per query. Query as defined as when user stops tying and looks at results. Do you know how to debounce the function call with this lib?

**Comment by kamok** [comment]
Doing something like the rxjs debounceTime doesn't work with your library for some reason:

```
  getResults(query: string): Observable<Address[]> {
    return this.http.get(`${this.apiUrl}/json?input=${query}&types=address&key=${this.googlePlacesAPIKey}`)
      .debounceTime(5000)
      .map((res) => res.json())
      .map((res: { predictions: Object[], status: string }) => {
        return Address.asAddresses({ objs: res['predictions'], type: 'GoogleAddressAutocomplete'});
      });
  }
```

From my understanding, this should make sure that the function only get's called after 5 seconds, and will cancel any calls that are pending. But this lib makes it so it fires immediately.

**Comment by kadoshms** [comment]
Thanks, this is something that I should look further into.
In the meantime, if you have any insight, please share it.

**Comment by kamok** [comment]
@kadoshms I found the solution. https://stackoverflow.com/questions/35991867/angular-2-using-observable-debounce-with-http-get

Basically, you have to define it on the call when you subscribe. I can't define it inside the http call's observable inside `getResults`. I looked at your source code, in `autocomplete.component.ts`, you need to add `.debounceTime(someNumberThatWeCanSetOnTheComponent)` to line 120. 

This should be a very easy feature...Can you do it? If not, I can give it a shot.

**Comment by kadoshms** [comment]
Any contribution would be appriciated!

**Comment by kamok** [comment]
Urgh dude... You already had a debounce option when you used the Ionic 2 search bar. I only realized it so late after making the gulp changes to build on my project's `node_module`. I'm gonna submit a PR to tweak the README instead.

**Comment by kamok** [comment]
PR made: https://github.com/kadoshms/ionic2-autocomplete/pull/64

**Comment by kadoshms** [comment]
Thanks Ill review it asap

**Comment by kamok** [comment]
@kadoshms You can close this when you're done. It's just some README changes nothing interesting.
