### ISSUE TITLE
no pipe found for boldprefix

### ISSUE THREAD

**Issue by mwiley63** [kadoshms/ionic2-autocomplete#6]
Hey thanks for the great work! And my apologies if this is a dupe of #4 and #5 .

I'm guessing due to the recent ionic update (2.1.0); boldprefix is not defined when loading the @AutoCompleteItem annotation.  I am confused by the instructions in the readme.  ionic 2.1 is using rc4 of Angualr2, and ngModule was introduced in rc5.

For now, I worked around this by commenting changing the code to the following in auto-complete-.item.componet.ts:

```
/**
 * Auto complete Item base class
 */
// @AutoCompleteItem({
//     template: defaultTemplate
// })
@Component({
    template: defaultTemplate,
    pipes: [BoldPrefix]
})
```

I realize this is an ugly hack and a more elegant solution should be pushed to the repository. 
I'm still new to Ionic2/Angular2/Typescript, so I look forward to seeing how this solution could be improved.

**Comment by kadoshms** [comment]
Nope it's not a duplicate, I'm on it!

**Comment by kadoshms** [comment]
Fixed
