### ISSUE TITLE
Cannot build the project: gulpfile missing

### ISSUE THREAD

**Issue by bushybuffalo** [kadoshms/ionic2-autocomplete#60]
While trying to build the project for using the changes I made in my pull request for the ngModel feature, I noticed that the gulpfile was missing.

In .gitignore, every .js file is excluded, so I guess this could be the reason why it went missing in the first place.

Of course this means that there is currently no way to build the project the way it is supposed to be built.

@kadoshms could you check that out please ?

**Comment by kadoshms** [comment]
fixed 328c2852c5e086ab46308346c5dc5ee8a537511f
