### ISSUE TITLE
clearOnSelect option

### ISSUE THREAD

**Issue by tcigrand** [kadoshms/ionic2-autocomplete#62]
I was going to make a PR to skip hiding the list on select and wanted to see if you see any reason not to do this.

We are selecting multiple items and showing a checkbox in the list next to the selected items, so we don't want the list to disappear after select.

If you see no issues with this, I'll create a PR for you to review.

**Comment by kadoshms** [comment]
Please make a PR :)

**Comment by tcigrand** [comment]
👍  What's the purpose of `documentClickHandler`? Just to dismiss the list if you click outside of the component?

**Comment by kadoshms** [comment]
yes indeed

**Comment by kadoshms** [comment]
@tcigrand I am closing this for now, let me know if your'e troubled by something.
