### ISSUE TITLE
clickHandler problem

### ISSUE THREAD

**Issue by lpeppe** [kadoshms/ionic2-autocomplete#66]
Hi,
I'm now testing my app on android and whenever I tap on an autocomplete item, I get this error:

![image](https://user-images.githubusercontent.com/16524788/27532188-b13c57b8-5a5f-11e7-9c9e-7c1f3674da6e.png)

The weird thing is that it works fine when I test the app via ionic serve

**Comment by kadoshms** [comment]
Thank you for letting me know, I will take care of this issue as soon as I can.

**Comment by kadoshms** [comment]
Well, I have already fixed this: 6b012da943ee30ff6126ac96ea1fde4afcac586e.
I will release a new version anytime soon.

**Comment by kadoshms** [comment]
Please install `npm install ---save  ionic2-auto-complete@1.5.1-beta` and let me know if this problem reoccures.

**Comment by lpeppe** [comment]
I'm not experiencing this problem anymore but the itemSelected event doesn't get triggered

**Comment by kadoshms** [comment]
Ok, I will look into it.
