### ISSUE TITLE
Update NPM Version

### ISSUE THREAD

**Issue by tcigrand** [kadoshms/ionic2-autocomplete#68]
Could you update the npm version? Hoping to use the recent changes I made and don't want to point to my fork.

**Comment by kadoshms** [comment]
why not? :)

**Comment by tcigrand** [comment]
Not sure if you're saying, "why wouldn't I update npm?" or "why don't you want to use your fork?" haha.

**Comment by kadoshms** [comment]
why not using your fork? ;)
I plan to release a stable new version somewhere soon but cannot be commitrd to a specific date,
bit I will do it as soon as I can.

Thanks for your contribution!
