### ISSUE TITLE
Uncaught (in promise): Error: No provider for CompleteTestService! Error: No provider for CompleteTestService! at injectionError

### ISSUE THREAD

**Issue by badrshs** [kadoshms/ionic2-autocomplete#69]
Hi , 
I'm getting this error , 
I tried alot but it didnt work 

when i use public` completeTestService: CompleteTestService `in the constructor I got this 

> 
> Runtime Error
> Uncaught (in promise): Error: No provider for CompleteTestService! Error: No provider for CompleteTestService! at injectionError (http://localhost:8100/build/main.js:1657:86) at noProviderError (http://localhost:8100/build/main.js:1695:12) at ReflectiveInjector_._throwOrNull (http://localhost:8100/build/main.js:3196:19) at ReflectiveInjector_._getByKeyDefault (http://localhost:8100/build/main.js:3235:25) at ReflectiveInjector_._getByKey (http://localhost:8100/build/main.js:3167:25) at ReflectiveInjector_.get (http://localhost:8100/build/main.js:3036:21) at AppModuleInjector.NgModuleInjector.get (http://localhost:8100/build/main.js:4004:52) at resolveDep (http://localhost:8100/build/main.js:11465:45) at createClass (http://localhost:8100/build/main.js:11329:32) at createDirectiveInstance (http://localhost:8100/build/main.js:11149:37)
> Stack
> Error: Uncaught (in promise): Error: No provider for CompleteTestService!
> Error: No provider for CompleteTestService!
>     at injectionError (http://localhost:8100/build/main.js:1657:86)
>     at noProviderError (http://localhost:8100/build/main.js:1695:12)
>     at ReflectiveInjector_._throwOrNull (http://localhost:8100/build/main.js:3196:19)
>     at ReflectiveInjector_._getByKeyDefault (http://localhost:8100/build/main.js:3235:25)
>     at ReflectiveInjector_._getByKey (http://localhost:8100/build/main.js:3167:25)
>     at ReflectiveInjector_.get (http://localhost:8100/build/main.js:3036:21)
>     at AppModuleInjector.NgModuleInjector.get (http://localhost:8100/build/main.js:4004:52)
>     at resolveDep (http://localhost:8100/build/main.js:11465:45)
>     at createClass (http://localhost:8100/build/main.js:11329:32)
>     at createDirectiveInstance (http://localhost:8100/build/main.js:11149:37)
>     at c (http://localhost:8100/build/polyfills.js:3:13535)
>     at Object.reject (http://localhost:8100/build/polyfills.js:3:12891)
>     at NavControllerBase._fireError (http://localhost:8100/build/main.js:48413:16)
>     at NavControllerBase._failed (http://localhost:8100/build/main.js:48401:14)
>     at http://localhost:8100/build/main.js:48456:59
>     at t.invoke (http://localhost:8100/build/polyfills.js:3:9283)
>     at Object.onInvoke (http://localhost:8100/build/main.js:4575:37)
>     at t.invoke (http://localhost:8100/build/polyfills.js:3:9223)
>     at r.run (http://localhost:8100/build/polyfills.js:3:4452)
>     at http://localhost:8100/build/polyfills.js:3:14076
> Ionic Framework: 3.4.2
> Ionic Native: ^2.9.0
> Ionic App Scripts: 1.3.7
> Angular Core: 4.1.3
> Angular Compiler CLI: 4.1.3
> Node: 7.2.1
> OS Platform: Windows 10
> Navigator Platform: Win32
> User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/59.0.3071.115 Safari/537.36

when I use  ` completeTestService: CompleteTestService ` as normal init value the code work without error unless I write something I will get 

`Cannot read property 'getResults' of undefined
`

**Comment by badrshs** [comment]
I Got the problem 

for me I Follow the documentation but  there is nothing written there for adding completeTestService inside app.module provider 

What i basically  did is inside providor 

` providers: [CompleteTestService]`

thanks

**Comment by KevinGurden** [comment]
Thank you... I was struggling with this as well
