### ISSUE TITLE
if json format is not array any suggestion

### ISSUE THREAD

**Issue by prasitnarkdee** [kadoshms/ionic2-autocomplete#72]
data.json response like
{"result":["United States Minor Outlying Islands","United States Minor Outlying Islands"]}
asume i cannot change provider format any suggest about http map

      .map(
        result =>
        {
          return result.json()
            .filter(item => item.name.toLowerCase().startsWith(keyword.toLowerCase()) )
        });

**Comment by kadoshms** [comment]
@prasitnarkdee as long as you return an array or an Observable things will work fine (on later versions Subject is also allowed).
Then, just manipulate the returned data a little bit, and it should work.
