### ISSUE TITLE
How to get  name, id and other meta of selected item?

### ISSUE THREAD

**Issue by parthustad** [kadoshms/ionic2-autocomplete#74]
How to get  name, id and other meta of selected item?

**Comment by parthustad** [comment]
when item is selected how to get id associated with it?

**Comment by kadoshms** [comment]
@parthustad using the `itemSelected` event you have full access to the selected item (passed as an argument to the callback function).

Example:

In the template:
`<ion-auto-complete .......  itemSelected="foo($event)"></ion-auto-complete>`

In the component:

```
foo(item) {
  // here you have a full access to the item properties
}
```

**Comment by parthustad** [comment]
Okay Thank You Very much

let me check this.

**Comment by parthustad** [comment]
your code is working

But what if i want to access selected item properties when button is clicked?
