### ISSUE TITLE
How to get selected item properties on button click?

### ISSUE THREAD

**Issue by parthustad** [kadoshms/ionic2-autocomplete#77]
How to get selected item properties on button click?

how to allow item to be selected from only list?

**Comment by kadoshms** [comment]
1. Will be supported in the next release
2. Will be supported probably in the future

**Comment by denzelwamburu** [comment]
@kadoshms  Am interested in this too. How do i initiate a function call for example after user clicks a result.

Thanks

**Comment by vasanth-qedquest** [comment]
`  <ion-auto-complete [dataProvider]="completeTestService" (itemSelected)="itemSelected($event)"></ion-auto-complete>`

**Comment by kadoshms** [comment]
You can use the `getSelection()` method.
