### ISSUE TITLE
Exception in AutoCompleteComponent.documentClickHandler

### ISSUE THREAD

**Issue by marcorinck** [kadoshms/ionic2-autocomplete#78]
I use autocomplete like this:

````
<div class="input-group">
    <ion-auto-complete [dataProvider]="objektAutocompleteService" #autocomplete
						                   (itemSelected)="selectObjekt($event)"
						                   [options]="objektAutocompleteService.options"></ion-auto-complete>
    <icon class="group-icon search-icon" [svgIcon]="'magnify'"></icon>
</div>
```` 

<icon> is my own icon component which is displaying a SVG icon which is styled to be inside the searchbar. When I click/tap on this icon this exception is thrown:

```` 
WohnungssuchePage.ngfactory.js:648 ERROR TypeError: target.className.split is not a function
    at AutoCompleteComponent.documentClickHandler (index.js:129)
    at Object.eval [as handleEvent] (WohnungssuchePage.html:18)
    at handleEvent (core.es5.js:11914)
    at callWithDebugContext (core.es5.js:13206)
    at Object.debugHandleEvent [as handleEvent] (core.es5.js:12794)
    at dispatchEvent (core.es5.js:8814)
    at core.es5.js:9406
```` 

The problem is that the target of the click/tap event is now of type svg where the className attribute is not a string but a SVGAnimatedString which does not have a split function. 

I have turned off pointer events for now so that the element doesn't receive any events anymore, but maybe you want to handle that more gracefully.

**Comment by kadoshms** [comment]
There's already a fix for that issue, will be published soon.
