### ISSUE TITLE
 Limit the return of only 3 items.

### ISSUE THREAD

**Issue by renanmoraes** [kadoshms/ionic2-autocomplete#79]
I need a specific return, today I just found a way to return 1 or all according to the documentation.

Is there any way for it to return limited results, for example 3?

**Comment by kadoshms** [comment]
My approach was not to limit the developers at all by letting them implement their own AutoCompleteService, meaning that these limits are totally up your implementation.
You can for instance fetch the data from the server, and then take only 3 relevent items and return them to the auto complete component.

Was I clear enough?
