### ISSUE TITLE
Unable to compile for Android

### ISSUE THREAD

**Issue by beardroid2005** [kadoshms/ionic2-autocomplete#8]
The plugin works if you use it with "ionic serve"

When try to build a platform, I received this error message

_Error: Unexpected value 'AUTOCOMPLETE_DIRECTIVES' declared by the module 'AppModule' 
ngc failed 
ionic-app-script task: "build" 
Error: Error_ 

I have include the plugin in my project with 
_"ionic2-auto-complete": "^1.3.1"_
in package.json

Ionic info:
Cordova CLI: 6.3.1
Gulp version:  CLI version 3.9.1
Gulp local:   Local version 3.9.1
Ionic Framework Version: 2.0.0-rc.1
Ionic CLI Version: 2.1.0
Ionic App Lib Version: 2.0.0-beta.20
OS: Distributor ID:     Ubuntu Description:     Ubuntu 16.04.1 LTS 
Node Version: v6.9.1

**Comment by kadoshms** [comment]
Thanks for your attention.
It is a real unfortunate issue regarding the total change of approach Angular decided to take while upgrading.
I will try to do my best to find a proper solution, in the mean time, feel free to update me if you find anything.

**Comment by mateullull** [comment]
Same issue. I think that the way is to add a `@NgModule` directive to the `directives.ts` file, but it still throwing errors.

**Comment by kadoshms** [comment]
Yes, all of those issues occured since Angular made a big change of concept when they introduced NgModule.
I hope to have a solution soon, as for the moment  I am not as available as I would like :(

If you have any idea, let me know!

**Comment by mateullull** [comment]
Look these interestings links about this issue:
https://medium.com/@isaacplmann/making-your-angular-2-library-statically-analyzable-for-aot-e1c6f3ebedd5#.8lf1cp2kj
https://medium.com/@isaacplmann/getting-your-angular-2-library-ready-for-aot-90d1347bcad#.70jamdjcz

**Comment by ragunathans** [comment]
Same issue. How can we overcome this issue?

**Comment by danielcamilo** [comment]
Same problem here... I really liked the component but my project can't wait so long, I'm going to use another one while this issue remains open... anyway, congrats for the initiative.

**Comment by kadoshms** [comment]
@danielcamilo thanks :)
I am currently super busy (school, job etc..) so I couldn't find the time for looking through this, but I am totally planing to some day.
Sorry for your inconvenience :(

**Comment by georgibakken** [comment]
Same issue here, when building with `npm run ionic:build --prod`

**Comment by DarioPescatore** [comment]
Hi, I still have the same issue, even with the version rc5. 

"Error: Unexpected value 'AUTOCOMPLETE_DIRECTIVES' declared by the module 'AppModule'"

Anyone who have found a solution?

**Comment by kadoshms** [comment]
Please check in the new version (1.4.0).
Iv'e just tested in my own Android device and it looked fine.
