### ISSUE TITLE
Getting xmhttp request error

### ISSUE THREAD

**Issue by rkmahale17** [kadoshms/ionic2-autocomplete#84]
My jason Looks Like this...

{"response_code": 200, "trains": [{"number": "11010", "name": "SINHAGAD EXP"}, {"number": "11011", "name": "LTT-NED EXPRESS"}, {"number": "11012", "name": "NED-LTT  EXP"}, {"number": "11017", "name": "LTT-KIK WEEKLY EXPRESS"}, {"number": "11013", "name": "COIMBATORE EXP"}, {"number": "11014", "name": "LOKMANYA TT EXP"}, {"number": "11015", "name": "KUSHINAGAR EXP"}, {"number": "11016", "name": "KUSHINAGAR EXP"}, {"number": "11018", "name": "KARAIKAL LTT EXP"}, {"number": "11019", "name": "KONARK EXPRESS"}], "debit": 1, "total": 10}

and am trying to get autopopulate like ( 11010) SINHAGAD EXP two things in single shot which should to able to search through bot name and number
and am using rc2 version
which u suggested earlier ....

my code is 

  .map(
        result =>
        {
          
         return result.json().trains
         .filter(item => item.name.toLowerCase().startsWith(keyword.toLowerCase()) )
        });

error descrption
XMLHttpRequest cannot load http://api.railwayapi.com/v2/suggest-train/train/nn/apikey/myapikey. Redirect from 'http://api.railwayapi.com/v2/suggest-train/train/nn/apikey/myapikey' to 'http://api.railwayapi.com/v2/suggest-train/train/nn/apikey/myapikey/' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:8100' is therefore not allowed access.

**Comment by kadoshms** [comment]
This is definitely an issue regarding to your API (seems like a CORS issue), you can look for it online :)
This is issue has nothing to do with this project :).
