### ISSUE TITLE
ionFocus and ionBlur?

### ISSUE THREAD

**Issue by marcorinck** [kadoshms/ionic2-autocomplete#85]
I'm trying to get notified when the searchbar gets focused and/or blurred. But everything I try doesn't work ... at all. i tried these:

````
<ion-auto-complete #searchbar .... (ionFocus)="focused()" (focus)="focused()" (ionBlur)="focused()" (blur)="blurred()"></ion-auto-complete>
````

````javascript
@ViewChild('searchbar')
autocomplete: AutoCompleteComponent;
....

focused() {
	console.log("focussed"); 
}
blurred() {
	console.log("blurred"); 
}

ionViewWillEnter() {
	this.autocomplete.inputElem.focus.subscribe(() => {
		console.log("focused");
	});
	this.autocomplete.inputElem.ionFocus.subscribe(() => {
		console.log("focused");
	});
	this.autocomplete.inputElem.blur.subscribe(() => {
		console.log("blurred");
	});
	this.autocomplete.inputElem.ionBlur.subscribe(() => {
		console.log("blurred");
	});
}
````

I get no exceptions or any warnings or output and my subscribe functions aren't called at all. Though I can see in the developer console that the eventemitters on the inputElem element have registered observers. 

How can I register a handler for the focus/blur event?

**Comment by marcorinck** [comment]
I found a working solution myself: I just subscribed to the right event source. 

In my above code I subscribed to autocomplete.inputElem but in fact I didn't use the ion-input and instead used the (default) searchbar.  

So when subscribing to events on the searchbar it works:

````javascript
@ViewChild('searchbar')
autocomplete: AutoCompleteComponent;
....

ionViewWillEnter() {
	this.autocomplete.searchbarElem.ionFocus.subscribe(() => {
		console.log("focused");
	});
	this.autocomplete.searchbarElem.ionBlur.subscribe(() => {
		console.log("blurred");
	});
}
````

When one uses the input Element via <ion-auto-complete [useIonInput]="true"></ion-auto-complete> one has to use the inputElem though.

Maybe you want to pass these events along on ion-auto-complete itself?

**Comment by kadoshms** [comment]
Yes, I will add these events in the next release.

**Comment by kadoshms** [comment]
added f2c53b0eed9ec27d9106307ddebaa301b928d9d8

**Comment by marcorinck** [comment]
thank you!  👍
