### ISSUE TITLE
Can't bind to 'dataProvider' since it isn't a known property of 'ion-auto-complete'.

### ISSUE THREAD

**Issue by rkmahale17** [kadoshms/ionic2-autocomplete#86]
polyfills.js:3 Unhandled Promise rejection: Template parse errors:
Can't bind to 'dataProvider' since it isn't a known property of 'ion-auto-complete'.
1. If 'ion-auto-complete' is an Angular component and it has 'dataProvider' input, then verify that it is part of this module.
2. If 'ion-auto-complete' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message.
3. To allow any property add 'NO_ERRORS_SCHEMA' to the '@NgModule.schemas' of this component. ("
  <br>

**Comment by kadoshms** [comment]
Did you import the module as specified in the docs?

**Comment by rkmahale17** [comment]
thanks again sir, i was kiddish 
i am again having one query that having this type of json
[{"name": "BSL-PUNE EXPRESS", "number": "11025"}, {"name": "PUNE-BSL EXPRESS", "number": "11026"}, {"name": "PUNE-DBG EXPRESS", "number": "11033"}, {"name": "DBG-PUNE EXPRESS", "number": "11034"},  

i want to search by no also and by name . And wants result both of them

**Comment by rkmahale17** [comment]
hey i done this..
import {AutoCompleteService} from 'ionic2-auto-complete';
import { Http } from '@angular/http';
import {Injectable} from "@angular/core";
import 'rxjs/add/operator/map'

@Injectable()
export class CompleteTestService implements AutoCompleteService {
  delay: number;
  labelAttribute = null;
  trainArray:any;
  constructor(private http:Http) {

  }
  getResults(keyword:string)
   {

    
   
   
     return this.sham(keyword).filter((item) => {
            return item;
    
        }); 
      

    }
  





   sham(keyword){
 
//console.log(this.autocompleteValue.searchbar);
   this.http.get("http://api.railwayapi.com/v2/suggest-train/train/"+keyword+"/apikey/myapi/")
   .map(res => res.json()).subscribe(data =>{
   var trainArray = [];
     this.delay = 0;
   //console.log(data.train[0].classes[0]['class-code']);
   var i = 0 ;
   var sham = [];
  for (var key in data.trains)
    {
      i = i + 1;
      if (i < 9)
        
    {  
   sham[key] =  data.trains[key].name +" "+"("+data.trains[key].number+")";
        }
   
else{

  break;
}
   


    }


    this.trainArray = sham ;
  
  
    });
   
   return this.trainArray;
  
  }
}


but first time search it cause error and for next entry in search shows result for first entry
Give me some advice

**Comment by rkmahale17** [comment]
i dont think app.module.ts plays any role here..............


i am getting the list like

suppose i write like pune ( now it  will search inside gint json from http)
[{"name": "BSL-PUNE EXPRESS", "number": "11025"}, {"name": "PUNE-BSL EXPRESS", "number": "11026"}, {"name": "PUNE-DBG EXPRESS", "number": "11033"}, {"name": "DBG-PUNE EXPRESS", "number": "11034"},
  
now what i want list contain both 
   BSL-PUNE EXPRESS (11025)
   PUNE-DBG EXPRESS (11025)
  
and best part is it is comming by above coding but late  .......
if i type something first it will gives me some error null variable ....

 if i type "pune" first and search now it will gives me result for last type words 
 
 My question is can we take two elements of same array like i have done earlier in given module......

  My suggestiion for improment of autocomplete 

  1. Can we limit the no of entries that we want to display  ..... so time lagging can be will decrease
  2. For android studio a library is their called Google volly for very fast  http request can we buld same for ionic 2  as user wants their auto suggestion withing secound and also the repsone  for every http request. 

Give me your answer  ..... 


And lot of thanks for helping me out .... my app is all about auto suggestions

**Comment by kadoshms** [comment]
@rkmahale17 do you still encounter this issue?

**Comment by kadoshms** [comment]
Closing due inactivity.
