### ISSUE TITLE
error typing Chinese in iOS device

### ISSUE THREAD

**Issue by jason-li-aichotels** [kadoshms/ionic2-autocomplete#88]
when I was trying to typing in Chinese, each keypress will add the whole sentence to the input box again and again. for example, when I was trying to type in 'niu yue' in the keyboard which represent the Chinese word of New York, then I got 'nniniuniu niu yniu yuniu yue纽约'. pls fix this bug. many thx!

**Comment by kadoshms** [comment]
Thanks, I will look into it

**Comment by kadoshms** [comment]
cold'nt reproduce in iOS 10.1, please lmk if this still occurs.
