### ISSUE TITLE
Error: Template parse errors: Can't bind to 'dataProvider' since it isn't a known property of 'ion-auto-complete'.

### ISSUE THREAD

**Issue by richardshergold** [kadoshms/ionic2-autocomplete#89]
I've installed the package ok and imported the module as per the docs but am getting the error: 

**Error: Template parse errors: Can't bind to 'dataProvider' since it isn't a known property of 'ion-auto-complete'.**

In app.module.ts I have

`import { AutoCompleteModule } from 'ionic2-auto-complete';`

and later on....

```
imports: [
    BrowserModule,
    AutoCompleteModule,
    HttpModule,
    IonicModule.forRoot(MyApp)
  ],
```

in my component template I have:

`<ion-auto-complete [dataProvider]="completeTestService"></ion-auto-complete>
`
and in my component.ts I have:

import { CompleteTestService } from '../../providers/CompleteTestService';`

and in the constructor:

`public completeTestService: CompleteTestService
`

And I have your example CompleteTestService.ts in /Providers

Anything I'm missing?

**Comment by richardshergold** [comment]
Please ignore - fixed it.  As I'm using the new LazyLoading structure I needed to import the module in my component's module file.

**Comment by mwvarela** [comment]
@richardshergold How did you fix it? I have the same problem.

**Comment by SimonBrazell** [comment]
Had the same issue, fixed it by importing the `AutoCompleteModule` in the specific page's `.module.ts` file instead of the `app.module.ts` file like so:

```
// pages/my-page/my-page.module.ts

import { NgModule } from '@angular/core';
import { IonicPageModule } from 'ionic-angular';
import { MyPage } from './my-page';
import { AutoCompleteModule } from 'ionic2-auto-complete';

@NgModule({
  declarations: [
    MyPage,
  ],
  imports: [
    IonicPageModule.forChild(MyPage),
    AutoCompleteModule
  ],
})
export class MyPageModule { }
```
Thanks for the tip!
