### ISSUE TITLE
1.5.2-release version not available on npm

### ISSUE THREAD

**Issue by bloron** [kadoshms/ionic2-autocomplete#93]
`npm view ionic2-auto-complete versions`

`[ '0.1.0',
  '1.0.0',
  '1.1.0',
  '1.1.1-0',
  '1.2.0',
  '1.2.1',
  '1.2.3',
  '1.2.4',
  '1.3.0',
  '1.3.1',
  '1.4.0-alpha',
  '1.4.0-fix-to-38',
  '1.4.0-rc1',
  '1.4.0',
  '1.4.1-rc1',
  '1.4.1-rc2',
  '1.4.1-release',
  '1.4.2-rc0',
  '1.4.2-rc1',
  '1.4.2-rc2',
  '1.4.2-release',
  '1.4.3-alpha',
  '1.4.3-beta',
  '1.4.3-release',
  '1.5.0-alpha',
  '1.5.0-beta',
  '1.5.1-beta',
  '1.5.2-beta' ]`

**Comment by kadoshms** [comment]
Thanks, will be fixed soon.

**Comment by kadoshms** [comment]
now available.
