### ISSUE TITLE
ng-template doesn't work if <ul> is used

### ISSUE THREAD

**Issue by sasfeat** [kadoshms/ionic2-autocomplete#94]
According to the README, I have to write something like this.
```
<ng-template #addresses let-attrs="attrs">
         <span [innerHTML]="attrs.data.delivery_addr | boldprefix:attrs.keyword"></span>
</ng-template>
<ion-auto-complete
                [template]="addresses"
                [alwaysShowList]="true"
                [options]="{'placeholder':'Адрес доставки'}"
                [dataProvider]="deliveryLocationsService">
</ion-auto-complete>
```
In this case, I have template in the DOM, but it does not shown unless I change `<ul>` to `<ion-list>` and `<li>` to `<ion-item>` and everything works fine. 

I use: 

```
"ionic2-auto-complete": "^1.5.2-beta"
"ionic": "3.7.0"
"@angular/core": "4.1.3"
```

**Comment by kadoshms** [comment]
@sasfeat Where is this ul in your code?

**Comment by sasfeat** [comment]
@kadoshms 
It comes from ng-template.  
```
<ion-auto-complete ... >
      <ion-input ...></ion-input>
      <ion-searchbar ... ></ion-searchbar>
      <ul>
          <li><span>...</span></li>
                           ...
      </ul>
</ion-auto-complete>
```

 If I change `<ul>` to `<ion-list>` at template of index.js file (line 168) - it works fine.

**Comment by kadoshms** [comment]
@sasfeat I am trying to understand how to reproduce / approach this issue, but I can't seem to, because I can't see anything wrong with the example youv'e provided.

**Comment by kadoshms** [comment]
Closing due inactivity.
