### ISSUE TITLE
autocomplete results hidden when the component used inside ion-list

### ISSUE THREAD

**Issue by Abenezer** [kadoshms/ionic2-autocomplete#95]
in this situations 
```
  <ion-list>
       <ion-item >
       <ion-auto-complete ...> </ion-auto-complete>
       </ion-item>
  </ion-list>
```
the result list is hidden (overshadowed)

**Comment by kadoshms** [comment]
This is an ionic issue, solved by adding a `item-content` attribute to the auto-complete component.
See https://github.com/ionic-team/ionic/issues/6880

**Comment by Abenezer** [comment]
the `item-content ` doesn't work for me. fortunately i found css work around 
`.overflow{
  contain:none;
  overflow: visible;
}`
then 
 `   <ion-item class="overflow">
   <ion-auto-complete ...> </ion-auto-complete>
       </ion-item>
`

**Comment by rsweny** [comment]
if the auto-complete is inside an ion-card I had to add this to the card: style="overflow: visible;"
