### ISSUE TITLE
Results not being rendered immediately on iOS

### ISSUE THREAD

**Issue by andrews05** [kadoshms/ionic2-autocomplete#96]
Running on an iPhone with iOS 10, latest version of ionic. I type in the input and can see in the console that the results are properly fetched from the server (getResults returns an observable) but no items are displayed (li elements are not created) until some sort of refresh is triggered, such as rotating the device or refocusing on the input.

**Comment by andrews05** [comment]
This is only happening when navigating to the autocomplete page after having scanned a qr. Very strange, still trying to figure out a workaround...

**Comment by kadoshms** [comment]
Yes it does sound odd :|
It doesn't occure on other scenarios ?

**Comment by andrews05** [comment]
No, it works fine if I haven't scanned a qr. I think this is not a fault of the autocomplete plugin, I might have to take it up with the qrscanner devs.

**Comment by kadoshms** [comment]
@andrews05 ok, please update me.

**Comment by andrews05** [comment]
After mucking around with various workarounds for a while I eventually came back to try to nail down the cause and found it's magically working correctly now. Whether it was fixed by various refactoring I did, package updates I may have done, or something else entirely, I have no idea.
