### ISSUE TITLE
Template Parse Error

### ISSUE THREAD

**Issue by sauravvj** [kadoshms/ionic2-autocomplete#99]
Hey @kadoshms, I am just using the same code piece that you have given in the example in my App. I am seeing the below error on the console.

<img width="986" alt="screen shot 2017-08-25 at 12 03 14 pm" src="https://user-images.githubusercontent.com/8511613/29724251-6d6d2e88-898d-11e7-9496-b099da719ed2.png">

**Comment by kadoshms** [comment]
@sauravvj can you please post your code? (all relevant parts)

**Comment by sauravvj** [comment]
Service -
`import {AutoCompleteService} from 'ionic2-auto-complete';
import {Http} from '@angular/http';
import {Injectable} from "@angular/core";
import 'rxjs/add/operator/map'

@Injectable()
export class CompleteTestService implements AutoCompleteService {

  labelAttribute = "name";

  constructor(private http: Http) {

  }

  getResults(keyword: string) {
    return this.http.get("https://restcountries.eu/rest/v1/name/" + keyword)
      .map(
        result => {
          return result.json()
            .filter(item => item.name.toLowerCase().startsWith(keyword.toLowerCase()))
        });
  }
}
`
Template -
`  <ion-auto-complete [dataProvider]="completeTestService"></ion-auto-complete>
`

app.module.ts
`imports: [
    AutoCompleteModule,
    IonicStorageModule.forRoot(),
    IonicModule.forRoot(MyApp, {
      backButtonText: '',
      platforms: {
        ios: {
          inputBlurring: false
        }
      }
    }),`

app.scss
`@import "../../node_modules/ionic2-auto-complete/auto-complete";
`

**Comment by sauravvj** [comment]
Sorry, I have closed it by mistake. Reopening it again. @kadoshms  Please have a look.

**Comment by sauravvj** [comment]
I got this issue resolved. I had to upgrade my app to Ionic 3 and dependencies to angular 4 and then I got the plugin working for me. Thanks anyways.
